### ISSUE TITLE
两个设备能不能发送消息呢，比如简单的文字和图片呢

### ISSUE THREAD

**Issue by tianshaokai** [Jasonchenlijian/FastBle#1]

**Comment by Jasonchenlijian** [comment]
当然能。针对时机设备的characteristic进行write和read

**Comment by tianshaokai** [comment]
@Jasonchenlijian  作者能不能对蓝牙的api 做一个系统的讲解呢？就像https://github.com/GcsSloop/AndroidNote 这个人做的一样，对蓝牙使用到的类做一个系统的讲解。我原来做过蓝牙手环，蓝牙打印机，还都是处于使用阶段可是对蓝牙的api 都不是很清楚，最近又出了什么低功耗蓝牙 ，希望作者考虑一下。
