### ISSUE TITLE
建议增加一个功能连接2个ble设备的，现在穿戴设备比如鞋子 都是一双的

### ISSUE THREAD

**Issue by Heyxiang** [Jasonchenlijian/FastBle#103]
建议楼主推出连接2个ble设备的， 我们现在的项目就是连接ble进行数据传输，牵涉到高并发，一个设备数据很容易被另一个设备的数据给覆盖，用队列 管理Queue<BluetoothGattElement> mSendQueue = new ConcurrentLinkedQueue<>();  但是很多地方代码冗余，不稳定很多小bug, 希望楼主能推出连接2个设备的功能，万分感谢。

**Comment by Jasonchenlijian** [comment]
非常感谢你提供的建议。
本框架的新版本（2.1.0）加入了多连接的API。
