### ISSUE TITLE
如何用手机同时连接多个蓝牙设备

### ISSUE THREAD

**Issue by liubei111** [Jasonchenlijian/FastBle#109]
手机作为蓝牙主设备，同时控制多个蓝牙从设备

**Comment by michael-3ivr** [comment]
同问，是创建多个BleManager吗？

**Comment by saintnever** [comment]
同问

**Comment by Jasonchenlijian** [comment]
对于扫描出来的BluetoothDevice对象，使用其connectGatt(Context context, boolean autoConnect, BluetoothGattCallback callback)方法就建立连接。所以想要建立多连接，就这样操作即可，非常简单。但蓝牙4.0有多连接的数量限制，是7。
编码上，可以维护一个多连接的管理类。
本框架的新版本（2.1.0）加入了多连接的API。
