### ISSUE TITLE
只能搜索到BLE设备吗？

### ISSUE THREAD

**Issue by TearBack** [Jasonchenlijian/FastBle#11]
RT，我尝试搜索手机的蓝牙，但是并没有搜索到手机的蓝牙，只显示了BLE设备的。是不是普通蓝牙设备，跟BLE设备是不一样，需要特别处理？

**Comment by Jasonchenlijian** [comment]
当然，这个框架只是搜索低功耗蓝牙设备的，内部使用的是startLeScan()，普通蓝牙搜索使用的是startDiscovery()。

**Comment by TearBack** [comment]
谢谢你的回复，再请教一下，回调的方法里面，连接成功，跟发现服务，两个是怎么使用的？有什么区别吗？

**Comment by Jasonchenlijian** [comment]
连接成功是与设备建立蓝牙的基础连接。发现服务是因为，Ble设备通信，需要通过与硬件蓝牙设备协议service及character等值来进行操作，就是去发现这些。

**Comment by TearBack** [comment]
非常感谢，Thanks
