### ISSUE TITLE
蓝芽连线状态调用

### ISSUE THREAD

**Issue by hui5368** [Jasonchenlijian/FastBle#110]
不好意思，
请问如果我要在每个activity去调用蓝芽的连接状态，我该怎么做？
（Example:  蓝芽连线后    A_activity显示 (蓝芽已连线或断开） >如果换页  B_activity显示  (蓝芽已连线或断开）

有人可以告诉我吗？

**Comment by Jasonchenlijian** [comment]
采用Android伤各种消息传递机制。
