### ISSUE TITLE
一个设备断开后，会收到ACTION_ACL_DISCONNECTED广播，时间会比较久，有没有缩短时间的方法？

### ISSUE THREAD

**Issue by michael-3ivr** [Jasonchenlijian/FastBle#111]
Android的蓝牙侦测到设备端断开了，会发送ACTION_ACL_DISCONNECTED广播，APP收到广播后会重新扫描BLE设备，重新进行连接过程。从设备断开到Android发出ACTION_ACL_DISCONNECTED广播，时间会比较长大约16秒左右，大家有没有加快该通知时间的方法？

**Comment by dongweiq** [comment]
这个没办法的，其实蓝牙和手机直接是可以定一下这个断开时间提示的，但是有的手机没有适配这个协议，而是固定了一个断开提示的时长，不同手机不一样，小米手机好多都是8秒，有的oppo手机长达几分钟

**Comment by carozhu** [comment]
他那算是超时的情况吧
