### ISSUE TITLE
重新扫描的时候，总是扫描不到之前扫描的结果

### ISSUE THREAD

**Issue by TearBack** [Jasonchenlijian/FastBle#112]
我在使用scanDevice的时候，指定扫描12s。扫描结束后，可以选择重新扫描。然后又再次调起扫描，但是扫描到的结果都是跟前面的结果不一样的。
我只做扫描，并不做连接，读写等操作。
我尝试过closeBluetoothGatt，也尝试过BleManger置空，然后重新new。但是都没有效果。只有当我从新进入Fragment的时候，才可以扫描所有的结果，但是之后一样，扫描到的都跟前面的结果不同，扫到最后就是扫描不到任何结果，明明周围有十几个蓝牙设备。可以问一下，这是为什么吗？

**Comment by Jasonchenlijian** [comment]
试试用Demo推荐的方式：每次重新扫描的时候，都重新new一个ListScanCallback对象。

**Comment by TearBack** [comment]
非常感谢，我也是刚刚尝试出来了，可行，3Q

**Comment by zhufui** [comment]
为什么我用demo扫描出的结果跟系统设置中扫描出的结果不一样呢？

**Comment by Jasonchenlijian** [comment]
Demo只扫描BLE模块
