### ISSUE TITLE
小米6的蓝牙5.0经常掉线的问题

### ISSUE THREAD

**Issue by dongweiq** [Jasonchenlijian/FastBle#114]
公司测试机用的小米6，手机蓝牙版本是5.0，连接ble的时候总是经常断掉。但是有个奇怪的现象：如果手动拔掉遥控器的电池然后再放入电池，重新扫描就可以扫到。如果连接程序自己断掉重新扫描就会扫不到蓝牙设备了。然而我们使用nordic的官方软件却可以扫到并且能够连上

**Comment by dongweiq** [comment]
已解决，是重连方式的问题

**Comment by BestMafen** [comment]
@dongweiq 具体是怎么解决的呢？
