### ISSUE TITLE
请问我连接成功后，blueToothGatt.getServices()的返回值为什么为空啊

### ISSUE THREAD

**Issue by lavaguezf** [Jasonchenlijian/FastBle#115]
![qq 20170824190308](https://user-images.githubusercontent.com/20836587/29663694-fc9bf10a-88fe-11e7-924b-3365d8def98b.png)

**Comment by Jasonchenlijian** [comment]
如果要查询service，建议在 onServicesDiscovered(BluetoothGatt gatt, int status) 回调方法中去做操作，而不是onConnectSuccess(BluetoothGatt gatt, int status).

**Comment by LinkSy** [comment]
请问你找到这个方法了吗onServicesDiscovered

**Comment by lavaguezf** [comment]
![zofp7 vb 40up6zupzk2 d](https://user-images.githubusercontent.com/20836587/29696620-acf276fa-897c-11e7-9551-78f29202f44d.png)
