### ISSUE TITLE
你好。我并没有在BleGattCallback回调里面找到onServicesDiscovered()方法 请问是不是版本的问题

### ISSUE THREAD

**Issue by LinkSy** [Jasonchenlijian/FastBle#116]
同上

**Comment by MisterBowie** [comment]
我也是

**Comment by MisterBowie** [comment]
我也是

**Comment by Jasonchenlijian** [comment]
onServicesDiscovered()并不是强制必须复写的方法。如果需要，请手动复写。

**Comment by MisterBowie** [comment]
也没法重写,
对应的GATTcallback类
package com.clj.fastble.conn;

import android.bluetooth.BluetoothGatt;
import android.bluetooth.BluetoothGattCallback;
import com.clj.fastble.data.ScanResult;
import com.clj.fastble.exception.BleException;

public abstract class BleGattCallback extends BluetoothGattCallback {
    public BleGattCallback() {
    }

    public void onFoundDevice(ScanResult scanResult) {
    }

    public void onConnecting(BluetoothGatt gatt, int status) {
    }

    public abstract void onConnectError(BleException var1);

    public abstract void onConnectSuccess(BluetoothGatt var1, int var2);

    public abstract void onDisConnected(BluetoothGatt var1, int var2, BleException var3);
}

是导包为题吗?

**Comment by MisterBowie** [comment]
版本com.clj.fastble:FastBleLib:1.2.1

**Comment by Jasonchenlijian** [comment]
onServicesDiscovered() 是BluetoothGattCallback的方法。

**Comment by MisterBowie** [comment]
不好意思 没看见,我也看了BluetoothGattCallback类 过的快了没看见 studio复写的时候只看了BleGattCallback的能复写的方法  sorry
