### ISSUE TITLE
搜索设备时，无法搜索到身边的其它手机设备

### ISSUE THREAD

**Issue by AndroidBirdBoom** [Jasonchenlijian/FastBle#118]
大佬你好，我前几天使用这个框架的时候，打开蓝牙，也支持ble，但是就是搜索的时候只能搜出mac的设备，搜不到Android的设备，一个都搜不到，请问是啥情况？

**Comment by AndroidBirdBoom** [comment]
之前看到您关闭的comments，现在不支持手机 连手机，请问现在还不行吗？

**Comment by Jasonchenlijian** [comment]
是的，当前的版本还没有加入这个功能。
