### ISSUE TITLE
每次连接成功之后过大概50秒就会断开连接

### ISSUE THREAD

**Issue by VickerChen** [Jasonchenlijian/FastBle#119]
08-31 16:17:21.778 15673-15685/com.moscase.shouhuan D/koma: 连接成功SWBLE-BABA0006
08-31 16:18:12.519 15673-16210/com.moscase.shouhuan D/koma: 断开连接ConnectException{gattStatus=8, bluetoothGatt=android.bluetooth.BluetoothGatt@a7d74f9} BleException { code=101, description='Gatt Exception Occurred! '}

**Comment by Jasonchenlijian** [comment]
可能是因为长时间无操作导致的
