### ISSUE TITLE
为什么indicateDevice有时候成功，有时候失败？

### ISSUE THREAD

**Issue by TearBack** [Jasonchenlijian/FastBle#12]
已经有输出设置成功，D/BleConnector: setCharacteristicIndication----true----success： true
但是最终方法返回的是false，而监听也没有成功。
使用的是同一个特征值来设置监听，为什么会这样呢？
遇到这样子的情况，需要怎么处理？

**Comment by Jasonchenlijian** [comment]
两次操作之间，建议间隔一段时间。
