### ISSUE TITLE
重连无反应

### ISSUE THREAD

**Issue by lubowen1990** [Jasonchenlijian/FastBle#121]
在onDisConnected方法中调用gatt.connect后，并没有进行重新连接。
` @Override
    public void onDisConnected(BluetoothGatt gatt, int status, BleException exception)
    {
             Logger.e("断开了连接");
             //bleManager.closeBluetoothGatt();
              gatt.connect();
     }`

**Comment by TimmyGzw** [comment]
我也有这样的问题, 断线重连直接去连接也会直接 onConnectFail()

**Comment by Jasonchenlijian** [comment]
此问题在新版本上已做了优化。
