### ISSUE TITLE
你好，请问我在write、notify时都出现异常 Characteristic not support是怎么回事，都是支持write和notify的，会有什么其他原因呢

### ISSUE THREAD

**Issue by lavaguezf** [Jasonchenlijian/FastBle#124]
![qq 20170918152921](https://user-images.githubusercontent.com/20836587/30532373-943a855e-9c86-11e7-928d-161a6bf87190.png)

**Comment by lavaguezf** [comment]
ErrorCode 102  
this character not support write!

**Comment by MisterBowie** [comment]
我也是  请问 解决了吗?

**Comment by santa-cat** [comment]
我也是，求指导

**Comment by MisterBowie** [comment]
等扫描获取到蓝牙服务了之后在进行读写,通知等操作

**Comment by tommyfeng** [comment]
回调了 onServicesDiscovered() 这里应该就是获取到了蓝牙服务吧，为啥还是出现102

**Comment by santa-cat** [comment]
使用单例就好了

**Comment by zktzktzkt** [comment]
UUID.fromString(Config.char2),

**Comment by zktzktzkt** [comment]
ErrorCode 102
this character not support write!

请问这个怎么解决的

**Comment by yhjlsy123** [comment]
解决吗？问题在哪
