### ISSUE TITLE
调用readDevice 方法可以正常返回，但也伴随一个异常产生

### ISSUE THREAD

**Issue by hiperioncn** [Jasonchenlijian/FastBle#132]
调用readDevice方法时，BleConnector的setCharacteristicNotification方法中，
BluetoothGattDescriptor descriptor = characteristic.getDescriptor(formUUID(UUID_CLIENT_CHARACTERISTIC_CONFIG_DESCRIPTOR));
这句返回的总是null，造成notify operation failed异常产生。
请问这里为什么去掉了这段判断是否存在notify属性的代码：
int properties = characteristic.getProperties();
        if ((properties & BluetoothGattCharacteristic.PROPERTY_NOTIFY) == 0) {
            BleLog.w(TAG, "Check characteristic property: false");
            return false;
        }

**Comment by Jasonchenlijian** [comment]
原先的逻辑是： 如果这个characteristic同时都有read和notify两种属性，那么当对这个characteristic进行readCharacteristic的时候，先将notify关闭。你所列出的代码片段的确是有问题，因为如果要进行关闭notify的操作，肯定是要先判断一下是否存在notify属性的。
不过后面代码进行了更新修正，我将notify关闭这个操作去掉了，直接进行read。我进行了少量测试，看起来没有问题，但我对此不置可否，也希望大家给出意见。
