### ISSUE TITLE
关于scandevice的坑

### ISSUE THREAD

**Issue by qht1003077897** [Jasonchenlijian/FastBle#134]
提醒大家有个坑：

重写scandevice的notifyScanStarted方法的时候一定要写super.notifyScanStarted（）；，不然永远不会调用stopScan和onScanTimeout。

建议@Jasonchenlijian做出修改，避免想重写notifyScanStarted遇到这个坑。

**Comment by Jasonchenlijian** [comment]
好，谢谢，我会做一些优化。

**Comment by Jasonchenlijian** [comment]
2.0版本已优化
