### ISSUE TITLE
设备关闭后很久才能收到断开连接的通知

### ISSUE THREAD

**Issue by luziqi123** [Jasonchenlijian/FastBle#140]
首先非常感谢你能提供这么一套框架, 非常感谢.
其次就是我想问的那个问题 , 我通过心跳包可以及时知道设备断开了 , 但还没有收到断开连接的回调, 如果此刻再次打开设备进行连接就会非常慢!! 甚至拿不到服务...这个很让我头疼

**Comment by GoAheadComeOn** [comment]
非常感谢作者
请问在
void onFailure(BleException exception)： 操作或数据传输过程中出错；
  void onInitiatedResult(boolean result): 操作成功与否的回调；
请问onFailure和onInitiatedResult是互斥的吗

**Comment by Jasonchenlijian** [comment]
若onInitiatedResult失败，onFailure不会有回调。
