### ISSUE TITLE
关于onFailure和onInitiatedResult是否互斥的问题

### ISSUE THREAD

**Issue by GoAheadComeOn** [Jasonchenlijian/FastBle#142]
非常感谢作者

void onFailure(BleException exception)： 操作或数据传输过程中出错；
void onInitiatedResult(boolean result): 操作成功与否的回调；

你好我注意到onFailure为操作或数据传输过程中出错，onInitiatedResult为操作成功与否的回调
如果说操作失败的话是不是这两个方法都被回调？

**Comment by GoAheadComeOn** [comment]
请问连接断开之后的重连，需要stopNotify吗，还是说重连机制是不需要stopNotify的

**Comment by Jasonchenlijian** [comment]
若onInitiatedResult失败，onFailure不会有回调。打个比方，你练习射击：onInitiatedResult表示你的子弹有没有发射出去，onSucess和onFailure表示你的子弹有没有射中目标。

**Comment by GoAheadComeOn** [comment]
非常感谢

**Comment by Jasonchenlijian** [comment]
断开连接和stopNotify没有必然的联系。是否需要stopNotify根据你项目的实际情况来应对。打个比方，曾经有位同学做的项目是一台蓝牙血压计，设置notify血压计开启，stopNotify血压计关闭，假如断开连接的时候，不stopNotify也是可以，那这样血压计一直开启着。根据你自己的需求来进行操作。
