### ISSUE TITLE
一个特性有read、notify。就不能read。

### ISSUE THREAD

**Issue by santa-cat** [Jasonchenlijian/FastBle#150]

**Comment by Jasonchenlijian** [comment]
是的，你提的问题很好。之前的版本一直没有太多关注这一点，如果一个特性有两种操作，当对其进行第二种操作的时候，就会覆盖之前那个操作的数据。
解决方法是：
1. 如果使用的是2.1.0版本之前的代码，可以修改源码中的回调Hashmap的key值，原先的key值仅仅是这个特性的uuid，可以用uuid+操作属性替代。
2. 2.1.0版本之后已经修复这个问题。

**Comment by santa-cat** [comment]
我修改成新的版本后 connect之后 什么特性都不能操作

**Comment by Jasonchenlijian** [comment]
能贴一下走不通的部分代码吗？
