### ISSUE TITLE
扫描周围蓝牙设备

### ISSUE THREAD

**Issue by peiziliang** [Jasonchenlijian/FastBle#154]
手机自带的蓝牙扫描与软件扫描的差好多，而且软件有好多都扫描不到，蓝牙名称也获取不到。
手机是Android6.0的魅族手机
求大神解答。。。。。

**Comment by Jasonchenlijian** [comment]
手机自带蓝牙能扫描到经典蓝牙外设模块、BLE蓝牙外设模块，包括手机。而软件只扫描BLE蓝牙外设模块。至于蓝牙名称为空，是因为这个外设本来的广播名就为空。

**Comment by Arisono** [comment]
不支持扫描手机吗？？？

**Comment by Jasonchenlijian** [comment]
@Arisono 是的

**Comment by mshandan** [comment]
你好，我想知道如果只是依赖的话，怎么才能将搜索到的蓝牙列表显示出来，谢谢。
