### ISSUE TITLE
收不到通知

### ISSUE THREAD

**Issue by YanXiaosa5** [Jasonchenlijian/FastBle#156]
我调用设备的命令,写入的回调中显示成功,但是却没走notify的回调接口

**Comment by Jasonchenlijian** [comment]
你好，首先我不太清楚你那边与蓝牙硬件对接的协议。写数据的话很明显，一般是使用write方法，但硬件返回数据，是否是通过notify，这个需要你来确认。另外，notify的特征值是否确定用的是这个？还有就是，应该先进行监听，即notify，再进行write。

**Comment by YanXiaosa5** [comment]
是的,我是先打开通知,然后write,这个操作肯定是对的,因为这个操作成功过。
可是有的时候不走notify，有的时候又走了notify，不知道是为什么

**Comment by Jasonchenlijian** [comment]
可以试试用我提供的测试工具连接硬件，层别一下是否是你的代码运用写错了。

**Comment by newtonker** [comment]
@YanXiaosa5 Hi，我也遇到了这个问题，我这边是偶现的，偶发会出现write之后，Notify收不到的情况。跟设备对了一下交互过程，设备说发送了。感觉应该是手机蓝牙协议栈偶尔抽风了。

**Comment by QX-Zach** [comment]
我也遇到了，但是我们协议定义中的特性描述符不是2902，是自定义的36fb，其特性为36fa，这个会有影响吗？我已经修改了打开通知的方法，然后打开通知成功，但是无法收到通知。

**Comment by dsh923713** [comment]
我也遇到了，打开通知成功，但是无法收到通知。
