### ISSUE TITLE
我在pc上插了一个蓝牙适配器，扫不到。是不是因为提到的双模原因？

### ISSUE THREAD

**Issue by Huayra2** [Jasonchenlijian/FastBle#157]

**Comment by Jasonchenlijian** [comment]
你的问题我可能不能精确的找到问题。在PC上插一个蓝牙适配器，能否将这个蓝牙模块广播出去？广播的是否是BLE。我认为关键在于是否是BLE。我猜想很有可能是PC端BLE适配的问题，可能是驱动？

**Comment by Huayra2** [comment]
找到原因了，是没有广播，后来运行命令让它能够广播就可以扫到了
