### ISSUE TITLE
多次打开通知

### ISSUE THREAD

**Issue by YanXiaosa5** [Jasonchenlijian/FastBle#158]
请问,可以多次调用notify吗

**Comment by YanXiaosa5** [comment]
我在app的主页打开通知,然后跳到其他页面打开通知,再回到主页,就收不到通知了

**Comment by Jasonchenlijian** [comment]
1.notify打开的状态下可以再次调用打开方法
2. 是用的是Demo app吗？

**Comment by YanXiaosa5** [comment]
不是的,是在项目里使用的

**Comment by YanXiaosa5** [comment]
我的主页面是由四个Fragment组成的,跳转页面也是在Fragment中,但是返回到主页面，就收不到通知了

**Comment by Jasonchenlijian** [comment]
我认为是项目问题，是否切换的时候掉用了停止或移除方法。可以将代码贴出来分析一下。
