### ISSUE TITLE
建议:关闭连接时先移除callback

### ISSUE THREAD

**Issue by liaolintao** [Jasonchenlijian/FastBle#16]
在关闭当前连接的时候, 先移除callback, 再断开连接;因为断开连接会触发连接失败的回调.

 /**
   * 关闭连接
   */
  public void closeBluetoothGatt() {
    if (bleBluetooth != null) {
      bleBluetooth.clearCallback();
      bleBluetooth.closeBluetoothGatt();
    }
  }

**Comment by Jasonchenlijian** [comment]
建议很好！
