### ISSUE TITLE
本来发送20字节的数据可以成功，setMtu可以成功，之后发送数据不管小于20还是大于20都失败了

### ISSUE THREAD

**Issue by DCZLQR** [Jasonchenlijian/FastBle#163]
发送的数据超过20字节，setMtu可以正常回调函数，不过之后发送数据就失败了，不管是小于20字节还是大于20字节，请问这是什么回事

**Comment by Jasonchenlijian** [comment]
mtu设置了多少？回调了哪个方法？

**Comment by DCZLQR** [comment]
mtu为50，实际发送数据最长为27，可以调用onMtuChanged，不过失败后好像会自己改成23

**Comment by Jasonchenlijian** [comment]
onMtuChanged最终回调的数值就是当前设备可支持的mtu，假如还是23就说明不支持扩展。这个方法调用说明上有注释。

**Comment by hezhipengzipp** [comment]
onMtuChanged，这个回调你都没有保留出来。
