### ISSUE TITLE
how to learn status change ? 

### ISSUE THREAD

**Issue by ismailtosun** [Jasonchenlijian/FastBle#164]
how will i know  ble status when ble disconnect when i at different activity ?

**Comment by Jasonchenlijian** [comment]
1. publish-subscribe mode
2. EventBus @https://github.com/greenrobot/EventBus
3. Android Broadcast
4. Several activities binding the same service through bindService, then communicate with each other

**Comment by ruanbaojun1105** [comment]
+aidl
