### ISSUE TITLE
重复执行连接，断开操作，有一定概率会导致连接失败

### ISSUE THREAD

**Issue by wei1015** [Jasonchenlijian/FastBle#168]
公司要求写一个蓝牙连接自动测试的demo，对同一个设备进行数百次的扫描->连接->订阅->发送数据->数据回调->断开->扫描。。。的重复操作，在这中间会有一定几率出现蓝牙连接失败的情况，BleException内容是ConnectException{gattStatus=0, bluetoothGatt=android.bluetooth.BluetoothGatt@2e7fa3dc} BleException { code=101, description='Gatt Exception Occurred! '}，因为第一次接触Ble蓝牙，想问下这个异常可能由哪些因素引起的

**Comment by Jasonchenlijian** [comment]
'Gatt Exception Occurred! '的意思是连接出现了问题。gatt连接会受之前连接次数的影响。gatt断开，再次连接之前建议先调用一下close方法（在最近的几个版本中已经自动集成），然后在等待一段时间（如果短时间连接会造成相当长一段时间内一直连不上的情况）。总而言之就是：disconnect、close、wait、connect.
