### ISSUE TITLE
honor 6x，连接之后写数据马上就断

### ISSUE THREAD

**Issue by jinjianxin** [Jasonchenlijian/FastBle#169]
用华为honor 6x的手机连接，一写数据就断开了，不知道作者碰到过这种情况吗

**Comment by Jasonchenlijian** [comment]
遇到过，目前我的认知是和设备有关，和手机关系不大，我手头有几个设备经常一连就断，如小米手环。
当然这只是我的经验，我也排查了框架的因素，显然和框架关系不大，官方API的连接方法也就是那个。

**Comment by jinjianxin** [comment]
问题已经解决，和设备有点关系，在api 21 之后，可以动态调用gatt的requestConnectionPriority 这个函数去修改下这个参数，修改这个参数后，设备通信正常
