### ISSUE TITLE
请问一下是不是有的服务扫不到？

### ISSUE THREAD

**Issue by Huayra2** [Jasonchenlijian/FastBle#172]

**Comment by Jasonchenlijian** [comment]
你指的是同一个设备的某些服务吗

**Comment by Huayra2** [comment]
是的，我在linux上查看到我的ble设备有很多服务，有1112、1801、110e、1800、1200、110c、110b、110a，但是只扫到了1800和1801两个服务

**Comment by 4what2do** [comment]
是否是蓝牙缓存的原因

**Comment by Huayra2** [comment]
是linux端bluez的原因，后来解决了
