### ISSUE TITLE
提个issus

### ISSUE THREAD

**Issue by DCZLQR** [Jasonchenlijian/FastBle#173]
BleManager.getInstance().disconnectAllDevice();好像有问题，不能全部断开，必须遍历一遍已连接的设备，一个个断开，只有我这样？

**Comment by Jasonchenlijian** [comment]
好像没有能复现你的问题，你是如何调用那个方法的呢？可以展示一下你的代码。

**Comment by DCZLQR** [comment]
现在搞明白了，是因为我在viewpager里面使用这个方法，另一页也连接，默认缓存相邻的一页，所以没有断开
