### ISSUE TITLE
在android7.0下边做 扫描 停止扫描 开始扫描 停止扫描 重复操作 会出问题 扫描几次就扫描不到了

### ISSUE THREAD

**Issue by gitxiaojin** [Jasonchenlijian/FastBle#174]
在android7.0下边做 扫描 停止扫描 开始扫描 停止扫描 重复操作 会出问题 扫描几次就扫描不到了

**Comment by gitxiaojin** [comment]
BleManager.getInstance().cancelScan();
                //十次体重未变 则确定为终止体重值 否则继续扫描获取广播包
                if (i > 15 && weight > 0) {
                    if(r == 0){
                        showTipDialog(weight, r);
                    }else{
                        getWeightData(weight, r);
                    }

                } else {
                    scanDevice();
                }

**Comment by wei1015** [comment]
我也碰到过这种问题，在部分手机上会出现扫描过于频繁的log，后来发现两次扫描间隔4s左右就不出出现这种情况

**Comment by Jasonchenlijian** [comment]
间隔时间
