### ISSUE TITLE
同一个设备，Demo的notify方法可以成功，自己写的notify缺报timeout，所传的参数都是一样的，为什么呢？

### ISSUE THREAD

**Issue by pbaiyy** [Jasonchenlijian/FastBle#175]

**Comment by 4what2do** [comment]
2.1.5中demo里面有的方法和回调移除了吗？

**Comment by Jasonchenlijian** [comment]
你可以把相关代码贴出来，帮你看一下。

**Comment by hawkWei07** [comment]
@pbaiyy 是不是notify时传递的两个UUID的参数大小写问题？
我这边本地项目测试时，一开始传递的UUID全是大写的，永远time out，改成小写后就好了。
（之前集成的是1.2.x版本的，大写UUID能正常使用）

**Comment by Jasonchenlijian** [comment]
@hawkWei07 
好像是有这么个问题，非常感谢你提供的意见，这个问题会马上修复。

**Comment by pbaiyy** [comment]
@Jasonchenlijian @hawkWei07 确实是大小写的问题，已解决，谢谢。

**Comment by Jasonchenlijian** [comment]
v2.1.6已修复大小写的问题。
