### ISSUE TITLE
蓝牙连接成功后，占了太大的线程，导致我的视频预览很卡顿

### ISSUE THREAD

**Issue by shania-Li** [Jasonchenlijian/FastBle#178]
执行扫描蓝牙操作和连接蓝牙后，我的视频预览很卡顿，如果不连接就没事，连接之后就会导致我的预览视频很卡，我自己加了thread执行，也不管用

**Comment by shania-Li** [comment]
执行完BleManager.getInstance().scan();之后我的视频预览就只卡了一点点

BleManager.getInstance().connect();这个执行完之后，预览就完全卡得不行了

我该怎么办

**Comment by Jasonchenlijian** [comment]
scan和connect都是在主线程中执行的，你的视频预览呢？

**Comment by shania-Li** [comment]
我是自定义的一个播放器，开启了一个Thread去播放的

**Comment by shania-Li** [comment]
我现在优化了一下，每次执行完scan和connect就睡眠100毫秒，write成功也睡眠100毫秒，效果就稍微好点了，没那么卡。我有个小小的建议，可以把蓝牙的操作不放在主线程执行吗，主线程工作量大的时候，会有点影响其它功能的执行。

**Comment by Jasonchenlijian** [comment]
不放在主线程中这个有很多人提到了，我也在修改框架，考虑到不同手机以及兼容性问题，部分操作只能放在主线程，部分手机上的部分操作在只能放在主线程，所以最初始统一把所有操作放在主线程也是为了稳妥和方便，目前正在验证修改，近期就会更新。

**Comment by shania-Li** [comment]
嗯，好的，谢谢你的分享
