### ISSUE TITLE
蓝牙兼容性问题

### ISSUE THREAD

**Issue by liulianshanzhu** [Jasonchenlijian/FastBle#179]
请问一下，这个蓝牙库的兼容性怎么样？三星小米华为锤子等这些没问题吧？？如果需要放到后台保持手机跟蓝牙设备的长时间连接，会不会断开呢？？

**Comment by Jasonchenlijian** [comment]
我个人试过很多机型，其他开发者也使用过很多，型号兼容性方面应该还可以，但并不保证百分之百，还是需要开发者自行验证和考量。长时间连接会不会断开，和手机和设备都有关系。
