### ISSUE TITLE
断开连接过一段时间才会有执行onDisConnected()

### ISSUE THREAD

**Issue by DCZLQR** [Jasonchenlijian/FastBle#180]
首先手机连接上蓝牙模块，然后蓝牙模块断电，一般需要5到10s才会执行onDisConnected，请问有没有方法可以立即执行呢？

**Comment by Jasonchenlijian** [comment]
时间长短取决于设备，建议从设备端考虑。

**Comment by DCZLQR** [comment]
果然，试了下其他厂商的设备，一般3s内会执行

**Comment by TimmyGzw** [comment]
你好 我现在也有碰到这种问题, 蓝牙模块断电,将近20s才会执行 onDisConnected
请问你的解决方法是什么呢?

**Comment by ruanbaojun1105** [comment]
一般3秒内会断开，是蓝牙设备的原因

**Comment by DCZLQR** [comment]
@TimmyGzw 换其他厂商的设备就OK了

**Comment by Bter** [comment]
这个在库这边是没办法的，库本身也是靠API回调告知，这个问题就别想了。
