### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by WeichengXu** [Jasonchenlijian/FastBle#182]
您好，尝试使用最新的Demo同时连接4台蓝牙设备，出现如下问题：
1、对同一台设备快速点击连接多次，待连接后断开，就无法搜索到，这个应该是执行了两次connect，但是找不到途径销毁这种问题
2、连接4台、全部断开，反复几次，会有长时间连不上的情况。
请问，上述问题是否有办法修复？谢谢

**Comment by 4what2do** [comment]
android 系统做了限制  度娘 看看呗

**Comment by WeichengXu** [comment]
什么样的限制？

**Comment by 4what2do** [comment]
Sometimes there are changes that slip through the cracks and don’t make the official list. One such change is protection against BLE scanning abuse in Android 7.The change prevents an app from stopping and starting BLE scans more than 5 times in a window of 30 seconds.
