### ISSUE TITLE
为什么我使用notify可以监听到数据，但使用indicate监听不到？

### ISSUE THREAD

**Issue by shania-Li** [Jasonchenlijian/FastBle#184]

**Comment by Jasonchenlijian** [comment]
是如何监听不到呢？ 是失败了吗，还是不返回数据？

**Comment by shania-Li** [comment]
打印了indicate success,但是onCharacteristicChanged这个没有数据返回，实际上蓝牙是不断给我发数据的

**Comment by Jasonchenlijian** [comment]
那你得看一看硬件协议了，确认一下设备是否会通过“那个indicate的特征值”给你发送数据。
