### ISSUE TITLE
快速且大量数据往蓝牙写数据异常

### ISSUE THREAD

**Issue by conanbo** [Jasonchenlijian/FastBle#187]
是否针对这种情况做消息队列处理？

**Comment by Jasonchenlijian** [comment]
是write吗？如果是连续写入，试试每次间隔10ms-100ms看看。

**Comment by conanbo** [comment]
我今天测试了一下，做消息队列处理，效果好很多，光进行发送间隔延时解决不了问题。
PS 我是连续发生音乐音符命令，数据传输的流畅度要求挺高的。

**Comment by Jasonchenlijian** [comment]
蓝牙数据读写是串行的，如果不等待上一次的结果回调而直接连续写入肯定是有问题的。
建议的操作是等待上一次动作完成后进行下一次。
