### ISSUE TITLE
只要硬件那边回应的数据超过20字节我就这边就一条数据也接不到

### ISSUE THREAD

**Issue by LiLingke** [Jasonchenlijian/FastBle#188]
你好，我这边只要硬件回应的数据不大于20个字节不需要分包的数据接收都没问题，可是只要是超过20个字节的数据我就一条都接收不到，可是硬件直接用调试工具又可以收到数据，app这边需要什么特殊处理吗？这个问题困扰我两天了，希望可以帮我解答一下，十分感谢

**Comment by zaoyilikai** [comment]
需要硬件分包发送，Ble包大小为20字节。

**Comment by Jasonchenlijian** [comment]
1. 方法一：在5.0以上，扩大硬件传输的MTU
2. 方法二：超过20字节，不仅APP向硬件发送数据需要分包，硬件回给APP也需要分包。APP收到分包后的多条数据后，根据硬件通讯协议进行组包，组成合适的长数据。

**Comment by LiLingke** [comment]
你好，很感谢你的帮助，我联系了有人（我用的蓝牙模块是有人公司提供的）的工作人员，他们给了跟你一样的解决方案，问题已经解决。再次感谢，你写的这个工具真的很棒，很好用
