### ISSUE TITLE
单例模式,引用了activity的上下文, 会引起activity内存泄露

### ISSUE THREAD

**Issue by liaolintao** [Jasonchenlijian/FastBle#19]
`  /**
   * 初始化
   */
  public void init(Context context) {

//    mContext = context;
    mContext = context.getApplicationContext();

    if (bleBluetooth == null) {
      bleBluetooth = new BleBluetooth(context);
    }
    bleBluetooth.enableBluetoothIfDisabled((Activity) context, 1);
    bleExceptionHandler = new DefaultBleExceptionHandler(context);
  }`

**Comment by Jasonchenlijian** [comment]
已修正，感谢。
