### ISSUE TITLE
2.1.6版本的，接收硬件分包发送的数据，会出现问题

### ISSUE THREAD

**Issue by pbaiyy** [Jasonchenlijian/FastBle#190]
比如一个包40个字节，硬件分2次发送，每个包20个字节，为包1，包2，然后，在onCharacteristicChanged中接收到的数据，会出现两段包2，包1不见了。

**Comment by Jasonchenlijian** [comment]
请改成2.1.7版本。

**Comment by pbaiyy** [comment]
@Jasonchenlijian 请问下。这个问题在2.1.7已经解决了是吗？

**Comment by Jasonchenlijian** [comment]
是的。

**Comment by pbaiyy** [comment]
好的，谢谢
