### ISSUE TITLE
错误里面打印成功

### ISSUE THREAD

**Issue by yishangfei** [Jasonchenlijian/FastBle#194]
![image](https://user-images.githubusercontent.com/15099278/34601727-36a5e156-f238-11e7-9952-0996427c72a1.png)
notify打开通知  开始写入   写入成功  进了写入错误的方法

**Comment by Jasonchenlijian** [comment]
不是onWriteSuccess吗？进入了写入错误的方法是什么意思？

**Comment by Jasonchenlijian** [comment]
可以打印错误信息查看 造成Exception的原因

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/34603394-bf0f0e36-f23e-11e7-8478-c6dc9e870fc1.png)
z这就是答应的getDescription打印的

**Comment by yishangfei** [comment]
找到问题了。。。。

**Comment by Jasonchenlijian** [comment]
kotlin的原因吗？

**Comment by yishangfei** [comment]
不是  哈哈哈 是我自己写错了         问一下写入超时可能是什么问题呀

**Comment by yishangfei** [comment]
gatt writeCharacteristic fail    Timeout Exception Occurred!      有时候会碰到这两个问题

**Comment by Jasonchenlijian** [comment]
超时没有收到写成功的回应
