### ISSUE TITLE
请教下，安卓4.X版本系统，扫描不出蓝牙广播名，另有4.x系统扫描不出蓝牙的解决办法

### ISSUE THREAD

**Issue by juenuo** [Jasonchenlijian/FastBle#195]
如题，在5.x系统以后的版本上能正常扫描出广播名，4.x系统扫描不出蓝牙广播名
附不是办法的办法，4.x系统点击扫描，手机按息屏，再点亮，蓝牙就出来了。

**Comment by zaoyilikai** [comment]
是在onStart进行扫描的么？

**Comment by Jasonchenlijian** [comment]
是用的这个框架扫描的吗？

**Comment by juenuo** [comment]
@Jasonchenlijian 是的  用你的apk，发现5.0版本一下的机器  listview在add蓝牙数据的时候有问题，其实扫描出来了，但是没有 添加数据集合。这也是楼下那些咨询为啥5.0一下的系统扫描不出来。具体为什么不显示我也没细看，搭楼主的福，直接提取出需要的代码了。。

另还有个问题问下，就是ble蓝牙我调用scanAndConnect扫描并且连接成功，写入了数据，但是不能快速写入，大概是3s写入一次，快于3S的话很大可能会写入失败。就像问下作者测试过的蓝牙能保持1s写入一次的频率吗？我现在3S每次的写入频率都会出现写入失败，然后就连接不上，得等个10几秒。如果别的蓝牙能要1s一次的频率 ，那我就要联系硬件方了。

**Comment by Jasonchenlijian** [comment]
读写数据是串行的方式，如果是连续写入大量数据，建议在保证已经得到上一条数据写入完成的回调之后在进行下一次读写。你所说的要3s才能保证成功我认为是设备原因。写入速度根据硬件的BLE版本有关，我试过大部分设备有10ms就能成功的。
