### ISSUE TITLE
ble和经典蓝牙连接的问题

### ISSUE THREAD

**Issue by XieYiGod** [Jasonchenlijian/FastBle#197]
楼主你好,有两个问题想请教一下您
1、请问经典蓝牙可以和ble通讯吗？我用您的库连接经典蓝牙连接上一会就断开连接了（大约1分钟以内），我想这个可能是ble和经典蓝牙的问题。因为我用过其他的库，他们的是一开始就连接不上，但是您的可以连接（我们公司最近需要通过手机蓝牙连接1个ble设备和两个经典蓝牙）。
2、手机通过ble可以和多少个设备连接？

**Comment by Jasonchenlijian** [comment]
1. 不可以和经典蓝牙通信
2. 一般是7个

**Comment by 4what2do** [comment]
2.2.1的远程库上  分包的wirte不在啊

**Comment by Jasonchenlijian** [comment]
应该是2.2.1没传成功，用2.2.2吧。

**Comment by 4what2do** [comment]
喔
