### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by yishangfei** [Jasonchenlijian/FastBle#198]
![image](https://user-images.githubusercontent.com/15099278/34755188-6a05f0ea-f5fd-11e7-9bba-f3caeb65e48a.png)
![image](https://user-images.githubusercontent.com/15099278/34755189-6dd30910-f5fd-11e7-8311-d4109c3a591f.png)
在华为荣耀上出现这个几率很大   其他手机基本上都能写入成功

**Comment by Jasonchenlijian** [comment]
连接成功后，可以试着等待一段时候后进行write。

**Comment by yishangfei** [comment]
没用。。。我每个写延迟了500ms    只是在荣耀上出现问题     还想请问有何办法能够加快速度连接

**Comment by yuchangfu** [comment]
我在华为p9上也是这个异常，请问解决了吗 @yishangfei
