### ISSUE TITLE
关于搜索连接

### ISSUE THREAD

**Issue by pbaiyy** [Jasonchenlijian/FastBle#199]
BleScanRuleConfig scanRuleConfig = new BleScanRuleConfig.Builder()
                .setDeviceMac(mac) 
                .build();
        BleManager.getInstance().initScanRule(scanRuleConfig);
        BleManager.getInstance().scanAndConnect
需要连接指定的蓝牙，使用上面这个扫描并搜索蓝牙的方法，搜索并连接的速度很慢，经常要超过10s，有什么优化的办法吗？

**Comment by 4what2do** [comment]
我是一点就连接  就是密码配对框
怎样可以拦截掉 网上有例子用广播  感觉有的手机上没用

**Comment by Jasonchenlijian** [comment]
方法很对，但速度我也不知道你为什么需要10s。你可以用其他工具，比如手机验证一下，是否真的是10s以后才会扫描到这个设备，我暂时不清楚你的问题出在哪。

**Comment by pbaiyy** [comment]
设备有存在说几秒对外发一次广播，可以被扫描到吗？

**Comment by Zhangxd77** [comment]
我也是要10s才能搜索完，

**Comment by Jasonchenlijian** [comment]
如果用scan方法，默认扫描时间是10s，这个扫描时长参数可以自己配置。
另外，可以在扫描到想要的设备后，自行调用停止扫描的方法。当然，这个逻辑可以用scanAndConnect替代，即扫描到即停止扫描然后直接连接。
