### ISSUE TITLE
您好,請教一個問題

### ISSUE THREAD

**Issue by ez32451** [Jasonchenlijian/FastBle#2]
請問一下,這個api可以連接microcontroller嗎？
手機設備的uuid和microcontroller好像不一樣
"fa87c0d0-afac-11de-8a39-0800200c9a66" 手機
"00001101-0000-1000-8000-00805F9B34FB" microcontroller
使用上會有差嗎？

**Comment by Jasonchenlijian** [comment]
对不起，我没有使用过microcontroller，你的问题我无能为力。
