### ISSUE TITLE
Is continuous scan possible? 是否可实现连续扫描

### ISSUE THREAD

**Issue by saintnever** [Jasonchenlijian/FastBle#200]
您好！我想实现连续扫描（scan window = scan interval），并实时更新各设备的RSSI值，想问应该怎样做呢？ 如果设备以30ms的间隔在连续广播的话，fastble能实现的最快rssi更新速度是多少？

**Comment by Jasonchenlijian** [comment]
可以在scan方法的`void onLeScan(BleDevice bleDevice)`中得到实时更新的设备，然后得到其RSSI属性。至于更新速度我没有认真测试过，希望你能验证得到答案。

**Comment by 957919019** [comment]
请问@saintnever  这个功能实现了吗？为什么我在更新的时候总是很卡，能贴一些代码参考一下吗？

**Comment by 957919019** [comment]
@Jasonchenlijian  这个函数没问题，更新频率我做了几次测试，同一个设备频率很快，因此使用`notifyDataSetChanged()`会造成Recyclerview刷新太快闪烁严重


>
