### ISSUE TITLE
在notify接收导数据后，post到主线程第一次刷新UI正常，第二次就没反应了，settext都没反应

### ISSUE THREAD

**Issue by qht1003077897** [Jasonchenlijian/FastBle#201]

**Comment by Jasonchenlijian** [comment]
能贴一下代码吗

**Comment by qht1003077897** [comment]
代码逻辑太复杂了，找到原因了：每write一次都必须先手动调用notify一次。如果只在连接成功后调用了一次notify打开通知，就出现我上面说的那种问题了。 
代码执行的好好的，也不报错，就是UI不更新。

**Comment by Jasonchenlijian** [comment]
有两个问题请问：
1. 你用的哪个版本的框架?
2. write和notify的特征是同一个还是不同一个?

**Comment by qht1003077897** [comment]
2.1.6      用的一个特征，支持write和notify。

**Comment by Jasonchenlijian** [comment]
我曾经在最初的1.0.x 的版本上研究过某个bug，便是同一个特征只会存在一种类型操作回调的问题。但是在2.1.6上不会有这个问题。
另外，我建议使用2.1.7，在notify高并发情况下，notify的数据可能会和之前的数据有干扰。我在release版本目录上已经去掉了2.1.6。但是这一点和你提出的问题应该没有关联。
我建议使用我提供的测试APK去验证你的问题，看是否需要每次都需要重启notify才能读到数据，我想是不用的。

**Comment by qht1003077897** [comment]
我当时最早使用的是1.2.1，是没有问题的。
我先改2.1.7吧，硬件做的是收到才notify，所以命令都是串行的，其实notify数据是没问题的，就是不知为何第二次、第三次更新UI没反应了...

**Comment by qht1003077897** [comment]
我改为2.1.7版本，上面的问题好了..............只需要打开一次notify，且UI也能正常更新了，看来源码还是改动了呀
