### ISSUE TITLE
connect方法好慢

### ISSUE THREAD

**Issue by pbaiyy** [Jasonchenlijian/FastBle#206]
从startconnect到connectsuccess，中间要间隔6秒钟，不知道是连接方法的问题，还是设备的问题呢？从06秒开始连接，到11秒才提示连接上
01-15 14:50:06.360 20303-20303/ E/String: String:onStartConnect
01-15 14:50:11.620 20303-20303/ E/String: String:onConnectSuccess

**Comment by Jasonchenlijian** [comment]
1. 设备相关
2. new BleScanRuleConfig.Builder().setAutoConnect(false)

**Comment by 4what2do** [comment]
我添加mac地址和设备名的过滤条件使用 自动连接可以连接，到时再把uuid添加进去过滤就连不上了，

**Comment by Jasonchenlijian** [comment]
注意是services的uuid

**Comment by 4what2do** [comment]
是服务的uuid  不是char的uuid 而且大小写试了都不行
