### ISSUE TITLE
bleDevice.getDevice().getUuids();拿不到uuid

### ISSUE THREAD

**Issue by Qiang3570** [Jasonchenlijian/FastBle#210]
ParcelUuid[] uuids = bleDevice.getDevice().getUuids();
扫描到设备后拿不到设备的uuid，是我方法用错了吗？我看只有这一个跟uuid相关的方法。

**Comment by Jasonchenlijian** [comment]
你要找的是什么uuids？

**Comment by 4what2do** [comment]
是不是只拿到了默认的2个特征uuid

**Comment by Jasonchenlijian** [comment]
uuid并不是通过BluetoothDevice对象获取的，是通过gatt获取的，可以一下这个库的方法说明。

**Comment by hezhipengzipp** [comment]
这个库真垃圾，居然这么多start
