### ISSUE TITLE
连接成功后 读取不到指定的服务，个别手机问题

### ISSUE THREAD

**Issue by xiaozhuge007** [Jasonchenlijian/FastBle#214]

**Comment by xiaozhuge007** [comment]
就是 我其他手机都可以读取到1000这个开头的服务 就我用的魅族手机读取不到这个服务

**Comment by 4what2do** [comment]
确定第一次连接设备。没有缓存

**Comment by z6499966** [comment]
你好，我遇到了和你一样的问题，同样是魅族，同样的读取不到指定服务，而且只有部分产品会出现这个问题，请问你有没有解决的办法。我被这个问题困扰了很久了。

**Comment by xiaozhuge007** [comment]
> 你好，我遇到了和你一样的问题，同样是魅族，同样的读取不到指定服务，而且只有部分产品会出现这个问题，请问你有没有解决的办法。我被这个问题困扰了很久了。

我已经用原生的自己写了
