### ISSUE TITLE
报错了有点凶啊哥

### ISSUE THREAD

**Issue by ruanbaojun1105** [Jasonchenlijian/FastBle#215]
![image](https://user-images.githubusercontent.com/7459297/35497724-54e39ad8-0506-11e8-849d-9a6b45f87e8f.png)

**Comment by ruanbaojun1105** [comment]
好用确实好用，我这几部手机是没测出这问题的，一上线半天就出来了

**Comment by ruanbaojun1105** [comment]
![image](https://user-images.githubusercontent.com/7459297/35498064-c0c85774-0507-11e8-978f-046cff4899b6.png)
这是出错方法
![image](https://user-images.githubusercontent.com/7459297/35498134-06590284-0508-11e8-9ae6-e53be30583c7.png)

**Comment by Jasonchenlijian** [comment]
compile 'com.clj.fastble:FastBleLib:2.2.4' 解决这个问题
