### ISSUE TITLE
有个问题请教一下

### ISSUE THREAD

**Issue by yygutn** [Jasonchenlijian/FastBle#216]
我发现Android上的蓝牙设备管理不好用,我现在遇到这个情况:2个蓝牙,一个支持蓝牙电话,一个支持蓝牙电话+蓝牙音乐,在同时勾选蓝牙电话(手机音频)的情况下,2个蓝牙不能同时连接;一个选择蓝牙电话,一个选择蓝牙音乐(媒体音频)的情况下,第二个蓝牙实际上是播放不出声音的........(在IPhone是可以的....而且音乐/来电打电话可以自己选择用哪个蓝牙)

所以突发奇想,能不能通过你的库写一个APP接管系统的蓝牙管理....实现自动识别音乐/来电情况然后切换蓝牙?如果可以的话,我就准备研究研究使用0-0

**Comment by yygutn** [comment]
下载安装DemoApk,打开扫描直接卡死........

**Comment by Jasonchenlijian** [comment]
在蓝牙扫描过程的回调方法中不建议做太多的操作，尤其是当设备数量很大的情况下。
此外可以使用 compile 'com.clj.fastble:FastBleLib:2.2.4' 解决这个问题。

**Comment by panyingdaoz** [comment]
蓝牙音乐实现了吗？
