### ISSUE TITLE
android 6.0及以后版本接收丢包

### ISSUE THREAD

**Issue by haiyin27** [Jasonchenlijian/FastBle#219]
接收100Hz，16字节的数据 notify，android 6.0及以后版本数据包接收丢包严重，丢失率在50%以上

**Comment by Jasonchenlijian** [comment]
请问你使用的是FastBle哪个版本？

**Comment by haiyin27** [comment]
是最新的版本

**Comment by haiyin27** [comment]
@Jasonchenlijian 已经解决丢包问题，通过硬件调整连接最大时间间隔，数据不再丢包。但是，android6.0及以上版本在几分钟之后会自动断开蓝牙连接，而6.0以下版本很稳定
