### ISSUE TITLE
希望能够增加获取蓝牙信号强度

### ISSUE THREAD

**Issue by mutouzhang** [Jasonchenlijian/FastBle#22]
希望能够增加获取蓝牙信号强度的功能

**Comment by edifangyi** [comment]
bleManager.scanDevice(new ListScanCallback(timeoutMillis) {
            @Override
            public void onLeScan(final BluetoothDevice device, final int rssi, byte[] scanRecord) {
                super.onLeScan(device, rssi, scanRecord);
//rssi 就是信号强度，可以创建一个类，装进去
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        MDevice mDev = new MDevice(device, rssi);
                        if (mDevices.contains(mDev)) {
                            return;
                        } else {
                            mDevices.add(mDev);
                            stateLayout.showProgressView("正在搜索...已搜索到" + mDevices.size() + "个设备");
                        }
                    }
                });

            }

            @Override
            public void onDeviceFound(final BluetoothDevice[] devices) {

            }
        });
