### ISSUE TITLE
How to achieve continuous RSSI read with FastBle?

### ISSUE THREAD

**Issue by DLeague9** [Jasonchenlijian/FastBle#221]
I connected with a Ble peripheral and after connection establish i called _BleManager.getInstance().readRssi(bd, rssiCallback);_ but its only called at once and break .

        scheduleTask4Rsii = Executors.newScheduledThreadPool(1);
        scheduleTask4Rsii.scheduleAtFixedRate(new Runnable() {
            public void run() {
                Log.i("Requesting Rssi: ",  "");
                BleManager.getInstance().readRssi(bd, rssiCallback);
            }
        }, 0, 1000, TimeUnit.MILLISECONDS);`

        final BleRssiCallback rssiCallback = new BleRssiCallback() {
        @Override
        public void onRssiFailure(BleException exception) {
            Log.i("Failed Reading Rssi: ", exception.getDescription());
        }

        @Override
        public void onRssiSuccess(int rssi) {
            Log.i("Device Rssi: ", rssi + "");
        }
    };
Please reply soon. thanks

**Comment by liudeming1122** [comment]
I meeting the same problem

**Comment by Jasonchenlijian** [comment]
compile 'com.clj.fastble:FastBleLib:2.2.4'
