### ISSUE TITLE
notify键值读取不准确

### ISSUE THREAD

**Issue by KingOfSu** [Jasonchenlijian/FastBle#224]
作者大大你好,我使用的是  com.clj.fastble:FastBleLib:1.1.1  版本的FastBle,其中读取notify的过程中,会出现读取notify键值不对的情况,比如我一个蓝牙键值为 1111  然后他也读取到了  但是读取的值另外的 0000  请问是延迟还是什么呢?请作者大大解答一下!!麻烦您了!!

**Comment by Jasonchenlijian** [comment]
我不是非常理解你的意思。notify的特征选取对了吗？对这个特征开启notify监听之后，是否有返回数据？假如是1.1.1版本，那么返回的数据应该通过characteristic.getValue获取，然后对byte[]进行解析，解析出来的结果是否符合你的要求？

**Comment by KingOfSu** [comment]
感谢作者大大的回复,我是按照您的以前的Demo进行修改的,键值读取是在连接成功的回调中,然后开启UI线程,使用了服务的notify方法,特征值是对的,解析出来的结果也的确是我的键值的值,但就是按键的键值与设备弹出的键值不太一样,如果是空闲情况下是没有问题的,当我用设备在摄像的时候,用遥控关闭摄像,这时候键值的读取就会出现不准确,所以想请问作者大大这是什么原因.

**Comment by KingOfSu** [comment]
就是我们的遥控有点击按键的时候的值,也有释放按键的键值,当摄像的时候,点击按键的值不见了,变成了两个释放按键的键值.作者大大

**Comment by KingOfSu** [comment]
请问可以加您一下吗?我好截图给您看看,感觉说可能有点不太清楚!

**Comment by Jasonchenlijian** [comment]
可以。
