### ISSUE TITLE
两部手机之间蓝牙连接

### ISSUE THREAD

**Issue by liyanmei** [Jasonchenlijian/FastBle#227]
一个手机A打开蓝牙设备，并设置在搜索范围内，另一个手机B打开蓝牙，并安装FastBle.apk，启动后，搜索设备，搜索不到手机A

**Comment by Jasonchenlijian** [comment]
这个框架目前不支持手机之间互相扫描

**Comment by wll2007** [comment]
为什么不支持？有什么不同吗？

**Comment by niubonan** [comment]
为什么手机之间不支持互相发现呢，现在的智能手机不都支持ble蓝牙了吗
