### ISSUE TITLE
发送一个包，但结果会返回多个包

### ISSUE THREAD

**Issue by fafala** [Jasonchenlijian/FastBle#229]
有个场景，发出去的数据为一个包，但返回结果有三个包，我此时需要对这三个包的数据进行截取拼接才能继续解析操作，这三个包是分三次在onCharacteristicChanged中返回回来的，我该如何拼接

**Comment by Jasonchenlijian** [comment]
三个byte[]拼接组合起来

**Comment by fafala** [comment]
嗯 我是通过打印日志才知道返回多少个包的，但是是否有办法知道每次返回的包个数？

**Comment by Jasonchenlijian** [comment]
返回多少包数据跟自身的蓝牙设备协议去沟通。实际返回多少包数据通过回调方法去数。

**Comment by fafala** [comment]
好的  谢谢啦

**Comment by fafala** [comment]
Jason 您好，发包成功后，若设备长时间无响应会有数据重发机制吗，比如说最多重发5次？

**Comment by Jasonchenlijian** [comment]
重发机制自己控制，设备是否无响应数据，多少时间无数据回复即认为无响应，都是可以由自己控制。框架本身仅提供发送成功或失败的回调通知。
