### ISSUE TITLE
sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by prohan-git** [Jasonchenlijian/FastBle#234]
java.lang.IllegalStateException: Handler (com.clj.fastble.scan.BleScanPresenter$ScanHandler) {1b0e6af} sending message to a Handler on a dead thread

at com.clj.fastble.scan.BleScanPresenter.onLeScan(BleScanPresenter.java:98)

这个是有影响么

**Comment by Jasonchenlijian** [comment]
功能上来讲没有影响，我会尽快在下个版本修复这个bug。

**Comment by Jasonchenlijian** [comment]
2.3.0版本修复这个问题。
