### ISSUE TITLE
通过 bluetooth 远程打电话的功能可以实现吗？

### ISSUE THREAD

**Issue by sunnyair** [Jasonchenlijian/FastBle#245]
我有一个手机和一个车机：（均为android设备）
手机：有sim卡，可以拨打电话
车机：无sim卡，不能打电话
我想实现这么一个功能：通过手机的蓝牙连接，直接在车机上打电话？
我查了些资料，有资料说hands free profile (hfp)是可以实现这个功能的，也有资料说目前android设备上的hfp协议实现不完整，目前还不能实现这个功能。
那么，具体是能实现还是不能实现这个功能呢？

**Comment by panyingdaoz** [comment]
这个功能实现了吗？
