### ISSUE TITLE
你好，遇到一个问题，看了好久还是没明白

### ISSUE THREAD

**Issue by yejuns** [Jasonchenlijian/FastBle#246]
为什么这样注册notify,最后显示不能注册notify,
log是特征值Notification通知回调失败:   BleException { code=102, description='descriptor equals null'}

这是我的代码
 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_operation2);
        btn=(Button) findViewById(R.id.send1);
        textView = (TextView) findViewById(R.id.show_data1);
        editText=(EditText)findViewById(R.id.write1);
        initData();
        getTarget();

    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public void initData(){

        bleDevice = getIntent().getParcelableExtra(KEY_DATA2);
        if(bleDevice==null){
            finish();
        }
        gatt=BleManager.getInstance().getBluetoothGatt(bleDevice);
        for (BluetoothGattService service : gatt.getServices()) {
            Log.e("--->",service.getUuid()+"");
            List<BluetoothGattCharacteristic> characteristics=service.getCharacteristics();
            for(BluetoothGattCharacteristic bc1:characteristics){
                Log.e("-->",bc1.getUuid()+" ");

            }

        }

    }

    public void getTarget(){
        Log.e("here","进入Target方法");
        BleManager.getInstance().notify(
                 bleDevice,
                "0000dfb0-0000-1000-8000-00805f9b34fb",
                "0000dfb1-0000-1000-8000-00805f9b34fb",
                new BleNotifyCallback() {
                    @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
                    @Override
                    public void onNotifySuccess() {
                        Log.d("success", "特征值Notification通知数据回调： "
                                + '\n' + Arrays.toString(characteristic.getValue())
                                + '\n' + HexUtil.encodeHexStr(characteristic.getValue()));
                    }

                    @Override
                    public void onNotifyFailure(BleException exception) {
                        Log.e("fail", "特征值Notification通知回调失败: " + '\n' + exception.toString());

                    }

                    @Override
                    public void onCharacteristicChanged(byte[] data) {
                        Log.d("success",new String(data));
                    }

                });

        BleManager.getInstance().indicate(
                 bleDevice,
                "0000dfb0-0000-1000-8000-00805f9b34fb",
                "0000dfb1-0000-1000-8000-00805f9b34fb",
                new BleIndicateCallback() {
                    @Override
                    public void onIndicateSuccess() {
                        Log.e("fail", "特征值Notification通知回调成功: " + '\n');
                    }

                    @Override
                    public void onIndicateFailure(BleException exception) {
                        Log.e("fail", "特征值Notification通知回调失败: " + '\n' + exception.toString());
                    }

                    @Override
                    public void onCharacteristicChanged(byte[] data) {
                        Log.d("success",new String(data));
                    }
                }
        );

    }

**Comment by yinanwang1** [comment]
发现虽然报错了，但是一样可以监听到内容，不影响正常使用。 @yejuns
