### ISSUE TITLE
连续读写,收到notify才写入下一条,有时会收不到notify

### ISSUE THREAD

**Issue by liu-xinhui** [Jasonchenlijian/FastBle#249]
连续读写,收到notify才写入下一条,有时会收不到notify. 只有再写入一条数据才收到notify,并且data包含两次回复的数据

**Comment by wendraw** [comment]
> 连续读写,收到notify才写入下一条,有时会收不到notify. 只有再写入一条数据才收到notify,并且data包含两次回复的数据

我现在也有这个问题，请问你解决了吗？
