### ISSUE TITLE
魅蓝手机测试(Meizu Metal1),扫描不到蓝牙设备哦~

### ISSUE THREAD

**Issue by jiangqqlmj** [Jasonchenlijian/FastBle#25]
魅蓝手机测试(Meizu Metal1),扫描不到蓝牙设备哦~

**Comment by Jasonchenlijian** [comment]
6.0以上的机型，额外添加权限：
ACCESS_COARSE_LOCATION、ACCESS_FINE_LOCATION

**Comment by jiangqqlmj** [comment]
我测试一下把，我的手机是5.0系统的，测试好了，回来反馈！

**Comment by Developmc** [comment]
Android6.0需要有定位权限才能搜索蓝牙
