### ISSUE TITLE
hello,i meet a question and i cannot solve it,please help me,thank you

### ISSUE THREAD

**Issue by yejuns** [Jasonchenlijian/FastBle#250]
i compile you module,then i meet this queston

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/clj/fastble/BleManager$BleManagerHolder;

**Comment by Jasonchenlijian** [comment]
Check in your project. Is there any other place that uses BleManagerHolder?

**Comment by yejuns** [comment]
thanks for your help,i have solved this question 2 mouth ago, i am sorry to reply your mail right now because i  just see the mail.
Your tip is right,the cause of the mistake is i had compile your library 2 times，thanks for your enthusiastic help again。 





At 2018-04-20 09:57:03, "陈利健" <notifications@github.com> wrote:


Check in your project. Is there any other place that uses BleManagerHolder?
