### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [Jasonchenlijian/FastBle#252]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by Jasonchenlijian** [comment]
I appreciate your support. I'm very happy that you can contribute to this project.

**Comment by anharismail** [comment]
Can I start designing the logo for this project now? @Jasonchenlijian

**Comment by Jasonchenlijian** [comment]
of course

**Comment by Jasonchenlijian** [comment]
Thanks

**Comment by anharismail** [comment]
Hello Sir, Thanks for using my Logo.

This is the editable files you need: https://drive.google.com/drive/u/1/folders/1Qc1JqHHE1-M2-CzdyRCpXEaTCBkl4sZH
