### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by zkpeng** [Jasonchenlijian/FastBle#253]
连接不上华为mate 9手机，点击连接后，onConnectionStateChange newState为STATE_CONNECTED，但过了大约一秒后 newState就成了STATE_DISCONNECTED了。

**Comment by zkpeng** [comment]
异常信息是：
ConnectException{gattStatus=133, bluetoothGatt=android.bluetooth.BluetoothGatt@423784c0} BleException { code=101, description='Gatt Exception Occurred! '}

**Comment by Jasonchenlijian** [comment]
就是说明真的断开了，设备原因吧？
