### ISSUE TITLE
关于write方法的一个warning

### ISSUE THREAD

**Issue by hiperioncn** [Jasonchenlijian/FastBle#258]
我使用不带split参数的write方法,写入了一个长度为60的字符串,自动分包发送了.
但是提示"Be careful: data's length beyond 20! Ensure MTU higher than 23, or use spilt write!"
于是查看了源码,默认情况下write的split就是true.
所以是否应该在write方法提示warning的判断中加入split == false的判断,既然已经split了,就没必要提示了
给使用者带来误解.
是否可以改为如下方式?
        if (data.length > 20 && !split ) {
            BleLog.w("Be careful: data's length beyond 20! Ensure MTU higher than 23, or use spilt write!");
        }

**Comment by Jasonchenlijian** [comment]
你的建议很好，我采纳，谢谢。
