### ISSUE TITLE
蓝牙获取设备名为NULL的问题

### ISSUE THREAD

**Issue by buyaomiege** [Jasonchenlijian/FastBle#259]

**Comment by Jasonchenlijian** [comment]
一般就是表示蓝牙广播名中内容为空。尝试找找厂商是否将设备名称放入了广播数据中。

**Comment by buyaomiege** [comment]
用手机系统的蓝牙搜素，可以找到设备的蓝牙名，另外如果设备名没有放在广播中，还会放在哪

2018-05-07 22:46 GMT+08:00 陈利健 <notifications@github.com>:
