### ISSUE TITLE
 minSdkVersion

### ISSUE THREAD

**Issue by zkpeng** [Jasonchenlijian/FastBle#261]
BLE android4.3(api 18)才提供的吧，FastBle的minSdkVersion怎么是14啊？适配到4.0了？

**Comment by Jasonchenlijian** [comment]
实际开发的大型app不可能仅支持4.3以上吧，2.3也可以啊，只不过使用BLE相关功能的时候，需要进行一下判断 `boolean isSupportBle()`，是否继续这个功能。

**Comment by zkpeng** [comment]
那就是说FastBle不能在4.3以下版本使用，4.3以下是不是只能用传统蓝牙？

**Comment by Jasonchenlijian** [comment]
是的
