### ISSUE TITLE
连接失败不停打印scan not started yet

### ISSUE THREAD

**Issue by hiperioncn** [Jasonchenlijian/FastBle#265]
连接设备失败，不停打印如下信息
BluetoothAdapter: stopLeScan()
BluetoothAdapter: scan not started yet
BluetoothAdapter: stopLeScan()
BluetoothAdapter: scan not started yet
BluetoothAdapter: stopLeScan()
BluetoothAdapter: scan not started yet

**Comment by Jasonchenlijian** [comment]
检查一下是否哪里频繁调用了cancelScan方法？

**Comment by Jasonchenlijian** [comment]
新版本已修复该问题

**Comment by longzekai** [comment]
> 新版本已修复该问题

还是一样啊，而且很奇怪的是，单独作为app调试没有问题，作为lib集成就必现。

**Comment by longzekai** [comment]
> > 新版本已修复该问题
> 
> 还是一样啊，而且很奇怪的是，单独作为app调试没有问题，作为lib集成就必现。

经过我的测试跟踪，发现如果在onScanFinished方法里调用了cancelScan 方法就必现这个问题。
