### ISSUE TITLE
连接失败的时间太长了！能否设置超时？

### ISSUE THREAD

**Issue by chuanjiangzhou** [Jasonchenlijian/FastBle#267]
连接失败的时间太长了！能否设置超时？

**Comment by Jasonchenlijian** [comment]
能，下个版本加上

**Comment by chuanjiangzhou** [comment]
@Jasonchenlijian 谢谢！辛苦了！

**Comment by jmloveyou** [comment]
我准备替换蓝牙模块，下个版本啥时候出来啊。

**Comment by Jasonchenlijian** [comment]
@jmloveyou 当前版本也是稳定版哦。

**Comment by jmloveyou** [comment]
请教一个问题啊，就是蓝牙是连上的，但是数据回不来，这个问题可能会出现在哪个环节呐，蓝牙模组那边能看到数据确实发给我了，但是我这边系统就是收不到。偶发性问题，只要频繁的断开，连接才会就会出现。

**Comment by jmloveyou** [comment]
请教一个问题啊，就是蓝牙是连上的，但是数据回不来，这个问题可能会出现在哪个环节呐，蓝牙模组那边能看到数据确实发给我了，但是我这边系统就是收不到。偶发性问题，只要频繁的断开，连接就会出现。

**Comment by Jasonchenlijian** [comment]
@jmloveyou 是用的这个框架吗？

**Comment by jmloveyou** [comment]
不是，是之前我们自己封装的。就是存在这个问题，所以我才考虑用您这个框架。

**Comment by Jasonchenlijian** [comment]
@jmloveyou 我不确定问题可能出在哪，也许是消息机制的问题吧，试试我这个框架吧。

**Comment by Jasonchenlijian** [comment]
v2.3.2版本加入连接超时。
