### ISSUE TITLE
怎么扫描某一特定的设备

### ISSUE THREAD

**Issue by scofieldwenwen** [Jasonchenlijian/FastBle#27]
请问一下: 在怎么通过 service uuid 扫描出特定的设备呢?或者说有没有其他方式扫描出某一特定ble设备.

**Comment by Jasonchenlijian** [comment]
原则上要先扫描连接到设备之后，才能得到UUID。 目前我不知道你所说的那种从后往前的方式。

**Comment by scofieldwenwen** [comment]
嗯,确实需要扫描连接之后获取到 UUID , 已经用调试工具获取到 UUID , 然后我是用 startLeScan(final UUID[] serviceUuids, final LeScanCallback callback) 这个方法来过滤 UUID ,从而实现扫描特定的设备

**Comment by yuanchenghao** [comment]
加在哪？能说一下么
