### ISSUE TITLE
连接后自动断开！

### ISSUE THREAD

**Issue by chuanjiangzhou** [Jasonchenlijian/FastBle#272]
版本:2.3.1
I/FastBle: connect device: name
           mac: 3C:A5:39:9A:AA:C5
           autoConnect: false
           currentThread: 2328
I/BluetoothDevice: connectGatt: 2
I/FastBle: BluetoothGattCallback：onConnectionStateChange 
           status: 0
           newState: 2
           currentThread: 2299
I/FastBle: BluetoothGattCallback：onServicesDiscovered 
           status: 0
           currentThread: 2299
E/MainWebActivity: onConnectSuccess: 0
I/FastBle: refreshDeviceCache, is success:  true
W/BluetoothGatt: Unhandled exception in callback
                 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGattCallback.onConnectionStateChange(android.bluetooth.BluetoothGatt, int, int)' on a null object reference
                     at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:181)
                     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
                     at android.os.Binder.execTransact(Binder.java:453)
E/MainWebActivity: onConnectFail: Timeout Exception Occurred!

**Comment by 4what2do** [comment]
是的 貌似是个严重的BUG啊  大佬给看看吧

**Comment by Jasonchenlijian** [comment]
的确是bug，2.3.1没有测试完全，请用回2.3.0版本，稍后会更新。

**Comment by Jasonchenlijian** [comment]
v2.3.2

**Comment by Muhammad-Soban** [comment]
I am facing same issue: Timeout Exception Occurred using v.2.3.2.

**Comment by Jasonchenlijian** [comment]
@Muhammad-Soban In the process of connection, or in the process of write?

**Comment by Muhammad-Soban** [comment]
In the process of connection

**Comment by docwei2050** [comment]
在 BleBluetooth类中加上状态判断
 case BleMsg.MSG_CONNECT_OVER_TIME: {
                    if (lastState == LastState.CONNECT_CONNECTED) {
                        return;
                    }
                    disconnectGatt();
