### ISSUE TITLE
有时会发生连接异常

### ISSUE THREAD

**Issue by MrLingGuiQin** [Jasonchenlijian/FastBle#278]
ConnectException{gattStatus=128, bluetoothGatt=android.bluetooth.BluetoothGatt@23ae2d35} BleException { code=101, description='Gatt Exception Occurred! '}

如上，扫描成功之后，设备正常开启可连接状态，偶尔会出现 连接失败，一直无法连接上的情况。

**Comment by zhongyiqwer** [comment]
同上，用起来很烦，连接成功，写数据和读的时候经常出问题，还老是跳出pin验证。我用测试软件测试过了。这个三分封装感觉问题太多了，我还是用原生的写一个把

**Comment by Jasonchenlijian** [comment]
如果配置重连，连接失败后可以自动重连。手动重连，可以不用扫描，直接对设备进行连接。
