### ISSUE TITLE
请问这个框架连接设备之后需要discoverService吗？

### ISSUE THREAD

**Issue by GreenhairTurtle** [Jasonchenlijian/FastBle#281]
如题，如果不discoverService的话直接getBluetoothGattServices(BleDevice)会把所有服务找到吗？

**Comment by Jasonchenlijian** [comment]
不会

**Comment by GreenhairTurtle** [comment]
谢谢回复

请问框架有discoverService的方法吗？
还是只能通过getBluetoothGatt(BleDevice)（或者onConnectSuccess）方法拿到gatt之后去discoverService吗？
如果是的话，请问onServicesDiscovered回调在哪里？

实在抱歉，我看了文档，但是没有找到

希望能够解答。谢谢

**Comment by Jasonchenlijian** [comment]
连接成功之后，会主动进行discoverService，所以当connectSuccess方法被回调时，即表示connect及discoverService已完成。

**Comment by GreenhairTurtle** [comment]
好的，明白了，再次谢谢
