### ISSUE TITLE
setAutoConnect 不生效

### ISSUE THREAD

**Issue by windouxp** [Jasonchenlijian/FastBle#282]
根据大佬的github demo 修改 .setAutoConnect(true）我的配置为自动连接，但是搜索的时候没自动连接（可以搜索到，不能自动连接）。点击连接就可以成功。不知道什么问题 ，是配置有问题吗？

**Comment by Jasonchenlijian** [comment]
setAutoConnect 并不是扫描完成自动连接。如果要扫描完成自动连接，请使用scanAndConnect方法。
