### ISSUE TITLE
退出app就会断开连接

### ISSUE THREAD

**Issue by seefutureLee** [Jasonchenlijian/FastBle#286]
您好，退出app后就会断开连接，不知道哪里出了问题

**Comment by Jasonchenlijian** [comment]
APP或Activity退出的生命周期中是否调用了 disconnect或者destory等断开连接的方法。

**Comment by 19861125** [comment]
昨天做了一些其他的测试  别的应用也会断开  估计是miui的问题  杀掉后台进程就会这样   多谢啦  我再试试别的手机
