### ISSUE TITLE
找到多个可写可通知的UUID，怎么获取有效的UUID？

### ISSUE THREAD

**Issue by renwfy** [Jasonchenlijian/FastBle#287]
难道拿到所有可写可通知的UUID ，尝试一遍？我手动选了下，发现最终有效的只有一个，但是怎么通过扫描得到的这些数据确定这个有效的UUID呢？

**Comment by Jasonchenlijian** [comment]
确定对应的UUID的用途，这些工作应该在于硬件端商定协议的时候确定好。实际开发中，针对某一款特定的设备，UUID甚至大多数情况下是固定写好在代码里，比如直接用这个UUID用来notify或者write，而不是获取所有UUID，一个个尝试。

**Comment by renwfy** [comment]
好的，谢谢
