### ISSUE TITLE
既然叫fastBle应该能够方便的进行多设备的连接管理才好

### ISSUE THREAD

**Issue by DreamerLeon** [Jasonchenlijian/FastBle#29]
只是建议~

**Comment by dongweiq** [comment]
同样希望支持多设备管理

**Comment by HeMing123** [comment]
我也需要管理多设备

**Comment by MoonlightSW** [comment]
@HeMing123 多设备管理不做是有原因得，高速通信得情况下，其他设备会断开连接~，无法保证稳定性

**Comment by HeMing123** [comment]
那就是说我们想做多设备连接，会遇到不稳定断开的坑，可有什么好的解决方案？

**Comment by MoonlightSW** [comment]
@HeMing123 直白的告诉你，经过我的测试，只是打个比方，类似与传送文件这种持续高速得蓝牙通信情况下，都会导致之前已经连接得还有当前连接得设备断开，android 和 ios都有同样的问题，如果不是高速传输，那就没关系，不过连接上限不同得android手机都不一样

**Comment by HeMing123** [comment]
你是怎么管理的多设备？能分享一下吗？

**Comment by MoonlightSW** [comment]
@HeMing123 集合咯，缓存Gatt对象，判断一下连接状态，断开连接的话就定时任务去重连

**Comment by MoonlightSW** [comment]
@HeMing123 记得要及时的关闭gatt连接，另外线程的话要注意内存泄漏之类的问题，做好停止标志

**Comment by HeMing123** [comment]
好的，谢谢

**Comment by Heyxiang** [comment]
@HeMing123  我公司的项目就连接多设备，一双鞋子，同时连接2个设备，高并发，用对列管理，有什么好的demo么

**Comment by michael-3ivr** [comment]
关注该问题，缓存Gatt对象有示例就好了，谢谢@MoonlightSW

**Comment by shimiso** [comment]
我也非常关注这个问题，目前设备采集血糖，血压，体重等多个常见健康类指标。因此APP需要同时集成多款设备

**Comment by Jasonchenlijian** [comment]
1.2.0版本已支持多连接。
