### ISSUE TITLE
不断的连接和断开服务最后连接上后，按键会出发多次通知回调

### ISSUE THREAD

**Issue by dongweiq** [Jasonchenlijian/FastBle#3]
估计callbacklist有问题，因为每次连接和设置通知会new一个新的callback实例，然后每次都add到callbacklist中，当触发按键的时候，callbacklist中重复的callback都会调用

**Comment by Jasonchenlijian** [comment]
很多的时候，你需要维持多个callback不停监听。当不需要该callback的时候，可以将该callback移除。移除方法，详见Usgae。

**Comment by dongweiq** [comment]
我看代码里有断开服务的时候removeCallback的操作，但是有的时候断开直接就异常了，没有调用到removeCallback方法，所以才会导致多个callback重复回调

**Comment by YiuChoi** [comment]
对啊，每连接一次就多一个

**Comment by Sunny22100486** [comment]
之前连接过，并且连接状态是BleManager.getInstance().isConnected() = true，但是再次扫描之后未连接任何设备，连接状态变成了BleManager.getInstance().isConnected() = false。其实之前的连接状态还是true，这是什么原因呢？

**Comment by imcloudwu** [comment]
的確斷開後重新連結會有多個callback,代表clearCallback()沒有效

試過stopListenCharacterCallback()也無效

**Comment by Jasonchenlijian** [comment]
新版已修复
