### ISSUE TITLE
回调处理的问题

### ISSUE THREAD

**Issue by playwind** [Jasonchenlijian/FastBle#30]
我的设备write 和 notify的uuid是一样的，hashmap的键值一样只能添加一个回调，导致收不到数据返回的通知(notify的回调被write覆盖了)

**Comment by Jasonchenlijian** [comment]
OK，你的情况我之前没有遇到过，我会考虑你的情况，进行优化。感谢。

**Comment by Jasonchenlijian** [comment]
新版已解决
