### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [Jasonchenlijian/FastBle#305]
![h ukg _8 j7xhk k w 7y](https://user-images.githubusercontent.com/25426589/43035968-838e8f94-8d2a-11e8-9e4b-4fa47edbfbe2.png)  
直接通过mac  报空指针  不是不用扫描吗  我这问题出在哪里呢 谢谢

**Comment by Jasonchenlijian** [comment]
有没有调用初始化方法？
