### ISSUE TITLE
setScanTimeOut()方法无效

### ISSUE THREAD

**Issue by lyp82nlf** [Jasonchenlijian/FastBle#307]
BleScanRuleConfig scanRuleConfig = new BleScanRuleConfig.Builder()
                    .setScanTimeOut(5000)              // 扫描超时时间，可选，默认10秒
                    .build();
            BleManager.getInstance().initScanRule(scanRuleConfig);
            mBlePresenterImpl.startScan();
在扫描前配置了扫描超时时间，但是
 private void startScanBle() {
        BleScanRuleConfig scanRuleConfig = new BleScanRuleConfig.Builder()
                .setScanTimeOut(10000)              // 扫描超时时间，可选，默认10秒
                .build();
        BleManager.getInstance().initScanRule(scanRuleConfig);
        bleManagerStartScan();
    }
库扫描函数又重置了10秒

**Comment by Jasonchenlijian** [comment]
因为 你在扫描前调用了setScanTimeOut(10000)，扫描超时时间按照最新一次的配置生效。
