### ISSUE TITLE
不满足多蓝牙连接需求~

### ISSUE THREAD

**Issue by georgeyang1024** [Jasonchenlijian/FastBle#31]
我所在公司做的app需要连接两个蓝牙，以后可能连接更多，看了一下您的开源项目，不支持多个蓝牙同时连接，所以建议您让这个项目支持多蓝牙同时连接功能。

**Comment by dongweiq** [comment]
我也在做相关的多个设备通过手机去控制😂，所以目前也是不支持多设备的控制，发现目前这个就是后边一个连接了然后之前连接的就无效了

**Comment by georgeyang1024** [comment]
我公也是多设备连接，用的每个SDK里面的封装方法，如果要自定义的话，我在网上看过好多个，觉得LiteBluetooth是比较合适的，如果你需要，可以去看看，他是一个实例对应一个蓝牙设备。
