### ISSUE TITLE
系统6.0，扫描设备能获取到mac以及其他信息，但是获取不到name

### ISSUE THREAD

**Issue by flyou** [Jasonchenlijian/FastBle#318]

**Comment by Jasonchenlijian** [comment]
针对同一台外围设备，其他系统（5.0或7.0）能获取到name吗？

**Comment by flyou** [comment]
手机自带的蓝牙可以获取到，你这个库获取不到。难道我还要刷个5.0或者7.0来试试?

**Comment by flyou** [comment]
换了三台手机 中兴、voio、和原生5.0  gg

**Comment by Jasonchenlijian** [comment]
如果不是手机系统版本的问题，那么我猜测，也许是这台设备并没有烧录名称在蓝牙广播名上面。你可以尝试去广播数据`byte[] scanRecord`中提取这台设备的名称，即Local Name。
