### ISSUE TITLE
获取蓝牙通知的疑惑

### ISSUE THREAD

**Issue by DeveloperHu** [Jasonchenlijian/FastBle#320]
当手机使用系统蓝牙连接至Ble设备时，知道设备的service和uuid_notify能获取该设备的蓝牙通知吗？
希望大大能解答一下，万分感谢

**Comment by Jasonchenlijian** [comment]
不能，蓝牙通讯过程中的核心之一就是BluetoothGatt，不连接无法得到coreGattCallback。
