### ISSUE TITLE
使用mac地址连接蓝牙，设置了setReConnectCount(1, 3000) ，实际不止尝试重连一次，会尝试N次直到成功

### ISSUE THREAD

**Issue by vae01** [Jasonchenlijian/FastBle#323]
使用mac地址连接蓝牙，设置重连次数setReConnectCount(1, 3000) 尝试重连一次，但是实际情况是只要连接失败就会 出现  E/FastBle: Connect fail, try reconnect 3000 Millisecond later这个log 然后就又重新连接，直到连接成功。而如果不设置setReConnectCount(1, 3000)  这个属性，那么连接失败就不会重新连接。这个情况不知道是不是我哪里没写对呢？

**Comment by kanshenmekan** [comment]
解决了吗，一样的问题

**Comment by Jasonchenlijian** [comment]
谢谢反馈，已在2.3.3版本中修复重连次数不重置为题。
