### ISSUE TITLE
想问一下，就是成功完成连接设备后，退出当前Activity 再扫描设备 就扫描不到了

### ISSUE THREAD

**Issue by Android1108** [Jasonchenlijian/FastBle#333]
想问一下，就是成功完成连接设备后，退出当前Activity 再扫描设备 就扫描不到了

**Comment by Jasonchenlijian** [comment]
连接成功后，如果不断开，那么重新扫描是扫描不到的。你需要确认一下，连接、断开的操作和你的Activity的生命周期是否一致。根据应用场景的需要，可以一致也可以不一致。

**Comment by Android1108** [comment]
> 连接成功后，如果不断开，那么重新扫描是扫描不到的。你需要确认一下，连接、断开的操作和你的Activity的生命周期是否一致。根据应用场景的需要，可以一致也可以不一致。

  BleManager.getInstance().disconnect(mBleDevice);

        BleManager.getInstance().destroy();
我已经 调用了这两句还是不行呢，大神看看还有什么问题呢

**Comment by Android1108** [comment]
> 连接成功后，如果不断开，那么重新扫描是扫描不到的。你需要确认一下，连接、断开的操作和你的Activity的生命周期是否一致。根据应用场景的需要，可以一致也可以不一致。

我把整个程序，退出 就可以 扫描到了

**Comment by Jasonchenlijian** [comment]
建议详细监控一下你在页面生命周期的调用情况，比如BleManager.getInstance().disconnect(mBleDevice)， onDisconnected， 是否真的被调用。不推荐在onDestory做太多操作，有时候会有坑。
