### ISSUE TITLE
设置重连setReConnectCount无效，并不会重连啊

### ISSUE THREAD

**Issue by dyalexamor** [Jasonchenlijian/FastBle#336]
setReConnectCount(3, 3000); 情况下开始扫描连接并没有进行重连啊；如何判定是否进行了重连？

**Comment by dyalexamor** [comment]
在使用mac直连，设置也没出现重连啊

**Comment by Jasonchenlijian** [comment]
此处的重连是指的连接失败的重连，并非连接成功后断开重新连接。可以查看logcat是否有Connect fail, try reconnect 日志出现。
