### ISSUE TITLE
android接收高频的音频数据传输时出现高丢包率

### ISSUE THREAD

**Issue by DeveloperHu** [Jasonchenlijian/FastBle#345]
我现在接收的是4KHz 125byte/package 的数据在本库下出现高的丢包率
查询后可以改变ble传输速率`BluetoothGatt.CONNECTION_PRIORITY_HIGH `
请问在本库中如何设置此状态 望大大能给予帮助，谢谢🙏！
@Jasonchenlijian 
参考资料：https://blog.csdn.net/hello_json/article/details/79541853

**Comment by lilingdan** [comment]
不用spp吗

**Comment by DeveloperHu** [comment]
还是用的ble 问题已解决
