### ISSUE TITLE
支持蓝牙串口通讯的设备相关问题

### ISSUE THREAD

**Issue by ErebusHu** [Jasonchenlijian/FastBle#35]
service UUID =  0000ffe0-0000-1000-8000-00805f9b34fb
characteristic UUID = 0000ffe1-0000-1000-8000-00805f9b34fb
这个UUID 是支持蓝牙串口通讯的 所以既需要notify 也需要write 
作者是每个characteristic 有且只有一个callback 。。
目前我是在write的callback的success中重新开启notify  但感觉会有实时性的问题。

**Comment by Jasonchenlijian** [comment]
可以同时操作notify和write方法，每个characteristic唯一对应一个callback。只要这个characteristic发生了数据变化，就会调用其唯一的callback。不论这个数据变化是write异或notify引起的。

**Comment by ErebusHu** [comment]
您好，【每个characteristic唯一对应一个callback】 我notify设置了callback 再设置write的callback后 notify的callback就失效了 不再调用了
