### ISSUE TITLE
老旧设备无法扫描出设备名称

### ISSUE THREAD

**Issue by PrinceChou** [Jasonchenlijian/FastBle#350]
我用大部分手机（近两年买的）都是可以搜到名字的，但是用16年的手机比如：三星S5、1加3等，虽然支持BLE4.0，但扫描出来没有Name，只有Mac。请问该如何解决呢？

**Comment by RunningShadow-007** [comment]
同问!求大神解答

**Comment by PrinceChou** [comment]
@RunningShadow-007 兄弟，我是因为没有判断定位是否开启导致的……扫描前必须要把定位打开。
