### ISSUE TITLE
楼主我在写入数据的时候报错

### ISSUE THREAD

**Issue by venusssss** [Jasonchenlijian/FastBle#352]
onNotifyFailure==BleException { code=102, description='descriptor equals null'}
onWriteFailure==BleException { code=102, description='this characteristic not support write!'}

**Comment by venusssss** [comment]
自己回复一下，已经解决了。

**Comment by dllen** [comment]
@venusssss 怎么解决的？

**Comment by venusssss** [comment]
> @venusssss 怎么解决的？
其实就是数据错误

**Comment by venusssss** [comment]
@dllen 其实就是要传输的数据错误

**Comment by dllen** [comment]
@venusssss 这个要怎么debug 数据是 byte[]

**Comment by venusssss** [comment]
@dllen Log
