### ISSUE TITLE
手机主动关闭并重新打开蓝牙

### ISSUE THREAD

**Issue by youjiadev11** [Jasonchenlijian/FastBle#363]
hi，你好我在用fastble 的时候，遇到一个问题，就是已连接状态下，主动关闭手机蓝牙再打开，然后设备怎样也连接不上了。

**Comment by Jasonchenlijian** [comment]
可以查看日志，是否是扫描不到？还是扫描的到连接不成功？ 如果是扫描不到，说明还连接着。尝试记住上一次连接设备的mac，然后使用直连mac的形式直接连接该设备，一般会重新连接。这也是很常见的重连解决方案。

**Comment by zaoyilikai** [comment]
先扫描到，再去连接。
