### ISSUE TITLE
oppor9m连接问题

### ISSUE THREAD

**Issue by shaohui93** [Jasonchenlijian/FastBle#374]
ble连接之后马上会断开，#OnDisConnected ] onDisConnected**status**0 Android 版本5.1

**Comment by shaohui93** [comment]
好像是发送数据之后就断开连接了。不发送数据就没有问题

**Comment by Jasonchenlijian** [comment]
会不会是因为你发了不合法的数据，设备主动断开连接了？

**Comment by shaohui93** [comment]
应该不会吧，都是发送的一样的数据，这个在别的手机上是没有问题的，还有一个问题 就是 有些Android手机比如魅族M5连接上ble蓝牙之后，过几秒中就会断开了，D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=5，这个是什么问题您知道么。

**Comment by shaohui93** [comment]
status=8 这个问题已解决，是在连接成功后马上开启sco,有概率会出现这个问题，连接成功后不开启是sco就可以了

**Comment by zhongtaotao** [comment]
你好, 我最近也是出现这问题, 你说的sco是指 "订阅通知notify" 么, 还是指其他的, 小米cc9e一直出现这个问题

**Comment by zhangzuofa** [comment]
> 你好, 我最近也是出现这问题, 你说的sco是指 "订阅通知notify" 么, 还是指其他的, 小米cc9e一直出现这个问题

你好这个最后 怎么解决  这个是指的什么
