### ISSUE TITLE
多设备连接的速度让我放弃了这个框架

### ISSUE THREAD

**Issue by KomoriWu** [Jasonchenlijian/FastBle#376]
多设备连接的速度真的很慢，目前还没尝试其它框架。但是nrf调试工具的速度要比fastble稳定和快几倍。
不过作者封装的蛮好的，用起来的确很方便。

**Comment by bulazhang** [comment]
有多慢啊！间隔能在秒级还是要到分钟级了？

**Comment by KomoriWu** [comment]
> 有多慢啊！间隔能在秒级还是要到分钟级了？

多连接时，连接到第三个第四个设备时，十几秒才能连上要么就超时了。nrf连接同样的设备七八个痘痕稳定平均两三秒一个

**Comment by xukun6868668** [comment]
nrf地址在哪

**Comment by shuile** [comment]
我最近也在开发Ble多设备连接，同样是连接速度慢的问题，请问你是怎么解决的呀？已经被iOS虐哭。。。

**Comment by KomoriWu** [comment]
我参考nrf代码改的，要比这个框架快很多

**Comment by KomoriWu** [comment]
https://github.com/NordicSemiconductor/Android-BLE-Library/
