### ISSUE TITLE
搜索不到支持BLE的设备

### ISSUE THREAD

**Issue by lxglife** [Jasonchenlijian/FastBle#377]
用其他的BLE库可以搜索到，使用这个库搜索不到。我看在issues中这个问题反馈挺多的，作者可什么好的建议

**Comment by zaoyilikai** [comment]
你是想用BLE和经典蓝牙设备通讯么？

**Comment by 957919019** [comment]
我是发生了使用华为荣耀8 Lite搜不到BLE设备，其他手机暂时没发生这种问题
