### ISSUE TITLE
有没有取消读写的接口？

### ISSUE THREAD

**Issue by 957919019** [Jasonchenlijian/FastBle#383]
我现在有一个问题，我在进入一个activity后要读好多次，然后在回调的时候setText显示到UI上，但是在读的过程中我退出了activity，此时有一个Thread在不停的读，destroy的时候改变thread的循环条件，此时setText()会报错，请问这个问题有什么好办法解决呢？

**Comment by 4332weizi** [comment]
用LiveData或者Databinding啊:smirk:

**Comment by 957919019** [comment]
改框架太下成本了 😏
