### ISSUE TITLE
程序建议

### ISSUE THREAD

**Issue by wzhsh90** [Jasonchenlijian/FastBle#4]
1、ListScanCallback 这个回调是在超时后才返回，如果设置超时10s或更大则回调太晚给用户体验不好
     建议直接返回blueDevice 
2、onLeScan device.getName()这个蓝牙名称不一定真实，需要对scanRecord进行分析得到localname才是真实的
3、增加对ble是否支持判断
4、增加对蓝牙状态监听处理
5、增加writeWithoutResponse
6、建议不用handler 进行主线程切换，建议使用org.greenrobot:eventbus:3.0.0

以上只是个人开发建议，有不当地方，还望详解。

**Comment by dongweiq** [comment]
作者已经改了第3、4个建议，而且对我提出的多个callback回调也写入了说明，反馈的好快👍

**Comment by wzhsh90** [comment]
蓝牙状态处理如果是在android5 以下是没有问题，但是android 6 就有问题了。

**Comment by tianshaokai** [comment]
线程切换可以用RxJava 和 RxAndroid

**Comment by jyz0025338** [comment]
2、onLeScan device.getName()这个蓝牙名称不一定真实，需要对scanRecord进行分析得到localname才是真实的

这个真的是有必要的。。。

**Comment by mendax92** [comment]
getName()经常没有值..

**Comment by Xanthuim** [comment]
@mendax92 难道真是楼上说的需要从scanRecord中分析吗？
