### ISSUE TITLE
102 exception

### ISSUE THREAD

**Issue by chuanjiangzhou** [Jasonchenlijian/FastBle#409]
大佬:这库还维护吗？
连续写数据的时候经常:BleException{code=102,description='gatt writeCharacteristic fail'}

**Comment by Jasonchenlijian** [comment]
在连续读写数据的时候，尝试中间增加短暂的延时，或者在writeSuccess回调之后再进行下一次write。

**Comment by chuanjiangzhou** [comment]
前面的一种方法已经尝识了，我试一下后面的一种方法。谢谢！
