### ISSUE TITLE
write写操作对于 换行 \n 会导致断开连接

### ISSUE THREAD

**Issue by BestCoderXQX** [Jasonchenlijian/FastBle#412]
String content = "asdasdasddasda\n123456\n\n下权限期限";

BleManager.getInstance().write(
                            bleDevice,
                            "E7810A71-73AE-499D-8C15-FAA9AEF0C3F2",
                            "BEF8D6C9-9C21-4C9E-B632-BD58C1009F9F",
                            content.getBytes("GBK"),
                            new BleWriteCallback() {
                                @Override
                                public void onWriteSuccess(int current, int total, byte[] justWrite) {
                                    // 发送数据到设备成功（分包发送的情况下，可以通过方法中返回的参数可以查看发送进度）
                                    Log.i("xqxinfo","发送数据成功,currnet"+ current + ",all:"+total+","+justWrite.length);
                                }

                                @Override
                                public void onWriteFailure(BleException exception) {
                                    Log.i("xqxinfo","发送数据失败："+exception.toString());
                                    // 发送数据到设备失败
                                }
                            });

Log 日志
发送数据成功,currnet1,all:2,20
 连接断开
发送数据失败：BleException { code=102, description='exception occur while writing: Timeout Exception Occurred!'}

测试 带有\n的字符串 ，只打印出第一个\n前的内容 之后就会断开连接 导致后面的打印不出来

**Comment by 330132662** [comment]
插眼 测了两次  暂时没遇到
