### ISSUE TITLE
[提问] ble蓝牙中那么多服务和特征，要怎么区别?

### ISSUE THREAD

**Issue by JoinBelieve** [Jasonchenlijian/FastBle#417]
我遇到了一个ble蓝牙，有两个特性都有 read、 write、 notify要怎么区分？

**Comment by xiaoguanghong** [comment]
这个要问蓝牙模块是怎么定义的, 我做过一个项目, 有3个特性, 每个特性的功能是不一样的, 你要控制哪个特性就往哪个特性发送数据, 注册哪个特性的notify

**Comment by JoinBelieve** [comment]
了解了 ，谢谢你
