### ISSUE TITLE
BleException { code=100, description='Timeout Exception Occurred!'}

### ISSUE THREAD

**Issue by JoinBelieve** [Jasonchenlijian/FastBle#418]
连接成功过一次蓝牙之后->断开蓝牙连接->再尝试连接蓝牙。就出现这个问题，出现频率多次。

**Comment by JoinBelieve** [comment]
connect device: SmartLock2
mac: 90:9A:77:0A:14:FB
    autoConnect: true
    currentThread: 2
    connectCount:1
BluetoothGatt: connect() - device: 90:9A:77:0A:14:FB, auto: true
BluetoothGatt: registerApp()
BluetoothGatt: onClientRegistered()
BluetoothGatt: cancelOpen()
BluetoothGatt: refresh()
BluetoothGatt: close()
BluetoothGatt: unregisterApp()

**Comment by JoinBelieve** [comment]
问题解决了，setConnectOverTime 时间设置长了就行了

**Comment by licc12** [comment]
"问题解决了，setConnectOverTime 时间设置长了就行了" 
楼上正解啊，强！

**Comment by runfengai** [comment]
> 问题解决了，setConnectOverTime 时间设置长了就行了

你好， 你设置的是多少呢，我看源码里边默认是10s.
