### ISSUE TITLE
提几点意见

### ISSUE THREAD

**Issue by Xanthuim** [Jasonchenlijian/FastBle#43]
最近也在学习蓝牙的知识，但是看了这个觉得还是很一般。
1、接口、抽象类太多，过多的抽象反而重了，而且抽象的也不是很好。比如扫描到的设备为什么要扫描结束后才返回结果而不是扫一个出现一个？另外，为什么不是用Set来去重而要用List做下判断去重？
2、封装也不是很好，比如连接服务就没必要公布出来让使用者去做。
`
@Override
public void onConnectSuccess(BluetoothGatt gatt, int status) {
          gatt.discoverServices();
}
`
2、没有考虑6.0权限这一块儿，存在权限安全问题。
其他的还没仔细看

**Comment by Jasonchenlijian** [comment]
感谢你的宝贵建议，新版已经修复了部分问题。
