### ISSUE TITLE
有时候会出现主动断开连接，再次扫描，扫描不到设备

### ISSUE THREAD

**Issue by JoinBelieve** [Jasonchenlijian/FastBle#438]
怀疑是没有断开连接，这个问题怎么解决呢？

**Comment by miluotao** [comment]
Android 7.0 以上系统不要在短时间内调用多次 startScan

理由：Android 7.0系统限制在 30s内最多只能扫描5次，用完之后在30s内是扫不到任何蓝牙的。

**Comment by JoinBelieve** [comment]
原来如此，谢谢
