### ISSUE TITLE
在Android4.4系统上连接蓝牙后，无法获取Service

### ISSUE THREAD

**Issue by ouyangshengduo** [Jasonchenlijian/FastBle#45]
在我的项目中，使用Android4.4.4的三星手机，连上蓝牙后，无法进入回调onServicesDiscovered，导致无法与蓝牙设备进行数据通信，发现在onConnectSuccess回调里面，没有调用bluetoothGatt.discoverServices()，增加之后，测试正常

**Comment by Jasonchenlijian** [comment]
详见Demo的使用。的确需要注意加上gatt.discoverServices();
