### ISSUE TITLE
this characteristic not support read!

### ISSUE THREAD

**Issue by xiaojidonggong** [Jasonchenlijian/FastBle#469]
1. 扫描指定名称的设备成功  
2.链接成功 
3.打开通知成功
4.接收数据，异常。
异常信息 “this characteristic not support read!”
我每一步的间隔时间是500毫秒，问题出在哪儿呢？

**Comment by lxa520** [comment]
你读的代码是怎样的？

**Comment by xiaojidonggong** [comment]
@lxa520 
自己解决了。我再notify中的onCharacteristicChanged(byte[] data)回调中接收到的数据
并不是使用data 
而是通过BluetoothGattCharacteristic.getValue() 拿到的。

蓝牙这块儿第一次做，read 和notify 不一样。场景不一样
