### ISSUE TITLE
连续read的话，有一些read不了，没有进入回调onCharacteristicRead

### ISSUE THREAD

**Issue by lizhongze123** [Jasonchenlijian/FastBle#50]
你好，看了demo是点击的时候再读的，如果我换了直接在发现服务成功后遍历读特征的话，后面的都读不出来的，没有进入onCharacteristicRead这个回调。就是如果每次只读一个的话就都可以成功，但是如果遍历读的话就只能读成功第一个，后面的都没有进入回调。想问下这个你是怎么解决的呢，感谢。

**Comment by Jasonchenlijian** [comment]
两次操作之间，建议延时一段时间。
