### ISSUE TITLE
重连不上，一直卡在onClientRegistered()，没有进入到onClientConnectionState()这一步，这是什么原因？

### ISSUE THREAD

**Issue by chen-fuhai** [Jasonchenlijian/FastBle#513]
D/BluetoothGatt: cancelOpen() - device: 5A:49:49:49:49:53
D/BluetoothGatt: refresh() - device: 5A:49:49:49:49:53
I/FastBle: refreshDeviceCache, is success:  true
    closeBluetoothGatt: 
D/BluetoothGatt: close()
    unregisterApp() - mClientIf=13
I/MainActivity: onConnectFail: BleException { code=100, description='Timeout Exception Occurred!'}
I/FastBle: connect device: null
    mac: 5A:49:49:49:49:53
    autoConnect: false
    currentThread: 1
    connectCount:1
D/BluetoothGatt: connect() - device: 5A:49:49:49:49:53, auto: false
    registerApp()
    registerApp() - UUID=d60d4b74-fd91-44dd-a04e-876694e1325e
I/MainActivity: onStartConnect
D/BluetoothGatt: onClientRegistered() - status=0 clientIf=13

**Comment by hike2008** [comment]
一样的问题，如何解决的呢
