### ISSUE TITLE
请教下，我先开一个notify监听，然后开个线程，每100ms就write一次，就报错了。

### ISSUE THREAD

**Issue by androidxu** [Jasonchenlijian/FastBle#54]
错误是：BleExceptionHandler: Initiated Exception Occurred!

**Comment by andy82302** [comment]
你好
可以請問你怎麼解決的嗎？
我同樣100ms寫一次
一開始都正常
但運行到一半就有點卡卡的
最後就沒動作了
但write的status完全沒改變
讓我不能做判斷

**Comment by Jasonchenlijian** [comment]
notify和write都是在UI线程中进行的吗？

**Comment by andy82302** [comment]
Notify一開始是按UI畫面 
後來改成都不用按 直接取得UI畫面的某個list格子

Write本來是broadcadtreceiver
接收到後直接寫資料出去

後來改成用Timer 100ms傳

一樣是同樣問題

不過接收都很棒 不會出錯

**Comment by andy82302** [comment]
抱歉 
我是新手
有很多不懂
