### ISSUE TITLE
请问不连接可以获得UUID吗?

### ISSUE THREAD

**Issue by ppg408331701** [Jasonchenlijian/FastBle#55]
我想在扫描阶段就获得所有扫描到的设备的UUID,但是BluetoothDevice.getUuids()返回的都是null.有什么办法吗?

我顺便表述一下我的需求,就是希望在扫描阶段就能得到一个唯一码,用来确认对象后,把唯一码传给后台,后台吧唯一码对应的数据返回给我,做一个类似身份识别的功能,不需要连接ble设备

**Comment by DCZLQR** [comment]
我也有同样的需求，请问你是怎么解决的
