### ISSUE TITLE
建议区分扫描状态和连接状态

### ISSUE THREAD

**Issue by nanixiaoseng** [Jasonchenlijian/FastBle#56]
当连接BLE设备后，很多设计场景下还会允许可以扫描，所以当扫描状态和连接状态同用connectionState时，则会出现connectionState重置为STATE_SCANNING和扫描超时后为STATE_DISCONNECTED，这时候的状态就有误了，因为此时和原设备还是连接状态，所以建议区分状态为connectionState和scanState。

**Comment by Jasonchenlijian** [comment]
新版已区分，感谢您的建议。
