### ISSUE TITLE
 你好，请教一个自动断开的问题

### ISSUE THREAD

**Issue by segatecm** [Jasonchenlijian/FastBle#63]
我写了一个安卓的ble的app，运行大概10秒左右就会自动断开，每次都是这样，提示错误是

D/BluetoothGatt: onClientConnectionState() - status=34 clientIf=5 device=A4:C1:38:77:18:15
I/cm: Disconnected from GATT server.

请问这是什么原因造成的？

**Comment by Jasonchenlijian** [comment]
10秒内是否有操作，自动断开也有可能是与你的设备有关。

**Comment by segatecm** [comment]
每隔50ms发送一次数据。是和ble模块有关还是和安卓设备有关？
是否安卓端ble初始化的时候有自动断开的设定？

**Comment by androidxu** [comment]
我也遇到了。。。

**Comment by Jasonchenlijian** [comment]
建议此类问题请从BLE外围设备找找原因。
