### ISSUE TITLE
bleManager.notify 运行线程的问题

### ISSUE THREAD

**Issue by iYoullloveGitHub** [Jasonchenlijian/FastBle#65]
bleManager.notify  如果在工作线程 运行,会出现
 Can't create handler inside thread that has not called Looper.prepare() 的问题,(子线程刷新ui的操作)
测试手机是 4.4 lenovoA936 , vivo xplay 4.4.4 . 
bleManager.notify  就是说要在ui线程执行吧

**Comment by Jasonchenlijian** [comment]
是的，bleManager的方法都需要再主线程中使用，有这个说明。
