### ISSUE TITLE
有很多手机搜索不到

### ISSUE THREAD

**Issue by cjcj125125** [Jasonchenlijian/FastBle#69]
看了代码用起来也感觉很方便，但是为什么和手机自带蓝牙不一样？比如自带蓝牙可以搜索到三个设备，但是你这个只能 搜索到一个，不知道你有没有发现这个问题，谢谢

**Comment by Jasonchenlijian** [comment]
这个框架只搜索BLE模块

**Comment by cjcj125125** [comment]
什么意思？没太懂？不应该是所有蓝牙设备多能搜索到吗？

**Comment by cjcj125125** [comment]
如果我想要手机和BLE模块都能搜索到，需要改哪里呢？？？谢谢

**Comment by Jasonchenlijian** [comment]
如果需要操作经典蓝牙，不建议使用这个项目。
