### ISSUE TITLE
您好 死活连不上  报这个错误是什么原因啊  

### ISSUE THREAD

**Issue by FengLinZhang** [Jasonchenlijian/FastBle#7]
连接失败或连接中断：
                                                        ConnectException{gattStatus=133, bluetoothGatt=android.bluetooth.BluetoothGatt@94d8028} BleException { code=201, description='Gatt Exception Occurred! '}

**Comment by SergioChan** [comment]
连接之前试着调用一下 GATTServer 的 close() 清除之前的连接试试？

**Comment by beiliubei** [comment]
+1

**Comment by Jasonchenlijian** [comment]
连接断开之后的重连很简单，在void onDisConnected(BluetoothGatt gatt, int status, BleException exception)调用boolean gatt.connect()方法即可，当外设再次处于可连接状态时，就会自动连上。
连接断开之后可以根据实际情况进行重连，但如果是连接失败的情况，建议不要立即重连，而是调用void closeBluetoothGatt()清空一下状态，并延迟一段时间等待复位，否则会把gatt阻塞，导致手机不重启蓝牙就再也无法连接任何设备的严重情况。

**Comment by BaoTaoGitHub** [comment]
俺也一样，俺也遇到一模不两样的问题~
