### ISSUE TITLE
Version：1.1.1断开后不能自动重连，之前可以

### ISSUE THREAD

**Issue by aystshen** [Jasonchenlijian/FastBle#71]

**Comment by Jasonchenlijian** [comment]
连接断开之后的重连很简单，在void onDisConnected(BluetoothGatt gatt, int status, BleException exception)调用boolean gatt.connect()方法即可，当外设再次处于可连接状态时，就会自动连上。
连接断开之后可以根据实际情况进行重连，但如果是连接失败的情况，建议不要立即重连，而是调用void closeBluetoothGatt()清空一下状态，并延迟一段时间等待复位，否则会把gatt阻塞，导致手机不重启蓝牙就再也无法连接任何设备的严重情况。
