### ISSUE TITLE
我试了几款手机，搜索不到。

### ISSUE THREAD

**Issue by thaixp** [Jasonchenlijian/FastBle#72]
4.0以上的系统手机应该就要BLE功能了吧，我也用API测了我手机支持这个功能，可是，我运行你的demo却搜索不到设备，好几部手机都是，这是什么原因呢，作者？

**Comment by ZacharyTech** [comment]
4.0 不支持BLE,4.3 才支持

**Comment by Qingtian239113** [comment]
首先,要确保你的手机支持ble,Android是4.3(API18)以上才支持,然后是6.0以上系统,需要动态申请定位权限,因为蓝牙是可以用来定位的
