### ISSUE TITLE
华为的Android 7.0版本都有问题

### ISSUE THREAD

**Issue by edifangyi** [Jasonchenlijian/FastBle#73]
我测试华为的三款设备都有问题，有的时候能连接上，有的时候不可以。有的时候链接上几秒就断掉。我不清楚是不是芯片的兼容性问题。

在其他比如海信上，也不稳定，但是比华为强。

用联想平板，一加3，还有HTC没有问题。小米待测

**Comment by Jasonchenlijian** [comment]
抱歉，我目前没有能力去测试这几款手机呢。如果你继续在开发，可以提一些建议和意见。
