### ISSUE TITLE
为什么bleManager.write只能在主线程里？

### ISSUE THREAD

**Issue by vicemiami** [Jasonchenlijian/FastBle#77]
为什么bleManager.write只能在主线程里？

**Comment by LT13S** [comment]
bleManager有个handle来处理消息，而这个handle是默认创建主looper里面的，所以只能在主线程里面使用，除非你给个子looper.

**Comment by vicemiami** [comment]
如果我一定要在子线程里进行 应该怎么写？或者怎么修改源码？

**Comment by LT13S** [comment]
在bleManager里面创建个子looper和handle绑定上，应该就可以了，你可以试试，我没试过。建议在主线程处理消息。
