### ISSUE TITLE
分包发送120K的数据，超多次连续写入后，会报101错误

### ISSUE THREAD

**Issue by vicemiami** [Jasonchenlijian/FastBle#79]
有时候发10几K就出错 有时候40多K，一旦出错，后面再发也是101，只要重启程序

**Comment by vicemiami** [comment]
现在发送间隔是20毫秒，如果加长间隔会好一些，但是不能再比20更慢了。。。

**Comment by vicemiami** [comment]
已解决

**Comment by AndroidBirdBoom** [comment]
您好，我做分包操作时，可以写入成功，但是失败率也很高，请问您是怎么进行分包操作并发送的，可以给个参考吗？

**Comment by vicemiami** [comment]
先把写入方式变为writenoresponse模式，每写一条，等待onCharacteristicWrite中的回调，回调后再写下一条，可以用countdownlatch来做 比较麻烦

**Comment by AndroidBirdBoom** [comment]
谢谢您，我尝试一下
