### ISSUE TITLE
Android6.0以上每次连接都是失败

### ISSUE THREAD

**Issue by yinbao** [Jasonchenlijian/FastBle#80]
由于蓝牙功能定制性有点高..不知道我是操作有误还是什么原因,我无法对库里面的代码进行微调...
问题:
1,蓝牙设备断开的时候,要过好几秒才回调断开连接
2,Android版本6.0以上无法连接成功,错误码为133
3,测试多台手机,5.1版本还是可以正常连接发送数据的.
4,蓝牙未开启进行搜索操作会导致ARN

**Comment by yinbao** [comment]
经过多次测试和断点调试.发现获取BluetoothGattService的时候为null,所以才导致连接失败.但是为什么6.0以下就没问题.

**Comment by Jasonchenlijian** [comment]
后来有测试过吗？ 和6.0没有关系吧？

**Comment by yinbao** [comment]
经过多次测试连接,是因为6.0会多发一些参数,导致模块那边不能识别,然后重新广播,导致连接失败 .暂时我们是在模块那边修改.@Jasonchenlijian
