### ISSUE TITLE
writeDevice之后回调的success怎么没有蓝牙设备响应的内容的？要怎么获取啊？

### ISSUE THREAD

**Issue by tyousyuka** [Jasonchenlijian/FastBle#81]
RT

**Comment by Jasonchenlijian** [comment]
write是 app to device.  read, notify, indicate是device to app.

**Comment by tyousyuka** [comment]
<img width="1171" alt="qq20170621-111315 2x" src="https://user-images.githubusercontent.com/5753432/27365422-a39b0afa-5672-11e7-97d1-fa992d7ae31c.png">
像这样吗，但是我执行完writeDevice再执行readDevice，readDevice的onFailure里面直接报错：BleException { code=101, description='Initiated Exception Occurred! '}，求指教

**Comment by Jasonchenlijian** [comment]
这个要看你硬件协议咯，到底用到了哪个特征？用的是read还是notify？

**Comment by tyousyuka** [comment]
@Jasonchenlijian 换notify也是了，什么返回都没有，求助

**Comment by Jasonchenlijian** [comment]
还是要看你的硬件通信协议咯，特征值用对了没有？

**Comment by tyousyuka** [comment]
@Jasonchenlijian 特征值不对的话，那writeDevice应该也不会有返回success了吧？

**Comment by Jasonchenlijian** [comment]
还是要看你的硬件通信协议，可能你的write是用对了。但device to app，是通过哪个特征值返回？是用的notify还是其他？ 如果是用notify，是不是应该先监听通知，即notify，再进行write？

**Comment by tyousyuka** [comment]
@Jasonchenlijian 好的，下午跟硬件的同时咨询一下，谢谢呀

**Comment by tyousyuka** [comment]
@Jasonchenlijian  现在用的都是红色里面的，扫出来有这些
<img width="1181" alt="qq20170621-135236 2x" src="https://user-images.githubusercontent.com/5753432/27369185-6e0930d0-5689-11e7-978f-320c45f20c27.png">

GATT 透传服务以及特征的 UUID如下，应该是怎么样的呀，同事也不懂，郁闷了，帮忙看看哇

<img width="818" alt="qq20170621-135254 2x" src="https://user-images.githubusercontent.com/5753432/27369201-7ebc8c74-5689-11e7-9543-2adb2bb82713.png">

**Comment by Jasonchenlijian** [comment]
你的硬件同事应该是最了解的，他应该告诉你device to app 用的是哪个特征值，用的是什么方式。 目前这种情况，你只能去一个个试了。 我建议你先用第三个特征值去notify，再用第四个特征值去write试试吧，祝你好运。

**Comment by tyousyuka** [comment]
@Jasonchenlijian onCharacteristicChanged没有回调，是需要什么操作嘛？

**Comment by Jasonchenlijian** [comment]
@tyousyuka 需要确认一下 你的外设是否真实地发送数据给APP了？

**Comment by xwpeng** [comment]
接不到外设给app发的数据
