### ISSUE TITLE
 连接以后打开通知notify(),在写数据writeDevice()就会报异常

### ISSUE THREAD

**Issue by moyihen** [Jasonchenlijian/FastBle#82]
连接以后打开通知notify(),在写数据writeDevice()就会报异常,  BleException { code=101, description='Initiated Exception Occurred! '}, 要是连接成功直接写数据,然后再打开通知就没事,但是notify()收不到响应数据 ,刚入BLE坑 求教...

**Comment by Jasonchenlijian** [comment]
连接之后，再notify， 再write，都是可行的，建议两两之间的操作，间隔一段时间，比如100ms。

**Comment by moyihen** [comment]
有试过间隔1秒 还是那个异常.. BleException { code=101, description='Initiated Exception Occurred! '},
