### ISSUE TITLE
notify中接收数据长度超过19位时，截取了我的数据，且替换了我的字符

### ISSUE THREAD

**Issue by qht1003077897** [Jasonchenlijian/FastBle#85]
我蓝牙模块向手机发送了32位数据，但是在notify中将数据再第19位截取了，notify的success方法调用了两次，并且将我发送的第19位的数据用数据长度替换了。

举个例子：比如我蓝牙模块将发送这些数据：

EB EB 1D 01 01 55 01 55 CC 0A CC 99 80 12 CE CC 80 01 02 03 04 05 06 07 08 09 10 11 12 13 B5 AA

在notify的success方法中将06这个字符替换为了09，代表09 后面有9个数据。

**Comment by fujingxie** [comment]
你好，我想问你一下你的notify是怎么配置的 我这边可以write成功 但是notify的回调一直没有@@qht1003077897

**Comment by Jasonchenlijian** [comment]
建议在硬件端使用分包传输避免这个问题。
