### ISSUE TITLE
使用求助

### ISSUE THREAD

**Issue by KingOfSu** [Jasonchenlijian/FastBle#89]
楼主是这样的，我也要做一个关于硬件方面ble，是关于按键的，使用您的App是可以读取到值的，所以我想直接跳转到那个notify那里读取好了，但是现在我就是连接上了设备，在发现服务的回调那里使用您的                        listen_notify() 这个方法发现不起作用，是我哪里有点问题嘛？不好意思啦

**Comment by Jasonchenlijian** [comment]
发现服务回调之后，注意两个细节。一个是延迟一点点时间，再一个是切换到主线程，再调用notify方法，试试看，祝你好运。

**Comment by KingOfSu** [comment]
是要切换到主线程问题，谢谢楼主，崇拜！

**Comment by KingOfSu** [comment]
我以为我打log就不用去主线程了呢
