### ISSUE TITLE
超过20字节的数据是这么处理的？

### ISSUE THREAD

**Issue by Kevin4ch** [Jasonchenlijian/FastBle#9]

**Comment by Jasonchenlijian** [comment]
分包处理。长度很长的数据应该会分成一个个包依次发送过来。根据与蓝牙硬件的通讯协议，一般在数据包头里应该会有一条完整的数据的数据长度标志位，通过这个长度截取数据即可。

**Comment by edifangyi** [comment]
接收发过来的十六进制字节超过20字节的，可以在作者 连接设备的 方法里，我是在onServicesDiscovered（final BluetoothGatt gatt, int status）方法里设置gatt.requestMtu(512);，即最大字节数，但是系统要超过5.0
