### ISSUE TITLE
你好，退出APP后再次连接搜索不到设备

### ISSUE THREAD

**Issue by kidcats** [Jasonchenlijian/FastBle#90]
你好，我在使用了您的库后用起来很爽，但是可能是我用法有问题，在退出APP后再次开启利用mac直接连接提示连接失败，错误日志是not found this device，手动扫描也是扫描不到设备，必须把设备断电重启后才能重新连接，并且可以利用mac自动连接，是我哪里用错了吗？如果有时间请回答下，谢谢

**Comment by Jasonchenlijian** [comment]
确保在推出之前，成功调用了closeConnect方法断开连接。你这种情况是因为手机蓝牙与设备的连接依然存在，所以搜索不到设备。

**Comment by kidcats** [comment]
好的，谢谢您了，我再试一下
