### ISSUE TITLE
Gatt Exception Occurred

### ISSUE THREAD

**Issue by 280017423** [Jasonchenlijian/FastBle#94]
1.手机连接蓝牙没有问题，uuid也设置没有问题
2.当我写入数据的时候没有反应，断点进去发现
public void onCharacteristicWrite(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status)
这个方法的状态值status 为 19，提示：Gatt Exception Occurred
3.手机是7.0的系统

**Comment by Jasonchenlijian** [comment]
可以展示一下写数据前后的代码吗

**Comment by shuijianbaozi** [comment]
这个问题 应该是没有分包导致的,不得超过20字节
