### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by crystal82** [Jasonchenlijian/FastBle#99]
首先感谢提供的库，简约很多开发时间。
使用过程发现，目前通过Add，Callback模式对ble相关操作设立监听，但是没有相应的移除方案，
在页面跳转时候容易出现内存泄漏。
多次仍旧不能完美改善，所以来探讨探讨。

**Comment by Jasonchenlijian** [comment]
谢谢你的测试及建议，后面的版本已经完善这方面的问题。

**Comment by fly263** [comment]
没有移除BleScanCallback这个的方法，这个会出现内存泄漏。
